In [58]:
import pandas as pd
from pathlib import Path

In [59]:
population2=Path ('population_2022.csv')

In [60]:
population2_df= pd.read_csv(population2)
population2_df.head (200)

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM,DP05_0090PE,DP05_0090PM,DP05_0091PE,DP05_0091PM
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P..."
1,1600000US0103076,"Auburn city, Alabama",80009,20,39138,1579,40871,1582,95.8,7.6,...,3.1,1.7,(X),(X),60600,(X),48.5,2.3,51.5,2.3
2,1600000US0107000,"Birmingham city, Alabama",196353,868,91868,2302,104485,2421,87.9,4.2,...,1,0.4,(X),(X),152283,(X),45,1.3,55,1.3
3,1600000US0121184,"Dothan city, Alabama",70524,678,33526,969,36998,913,90.6,4.5,...,2.7,0.9,(X),(X),52848,(X),46,1.3,54,1.3
4,1600000US0135896,"Hoover city, Alabama",92427,45,44454,2273,47973,2274,92.7,9.1,...,1.2,0.8,(X),(X),66535,(X),45.4,2.9,54.6,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1600000US0877290,"Thornton city, Colorado",143279,38,70280,2257,72999,2258,96.3,6.1,...,2.7,1,(X),(X),98340,(X),47.4,1.8,52.6,1.8
196,1600000US0883835,"Westminster city, Colorado",114539,39,59044,2287,55495,2287,106.4,8.5,...,3.2,1,(X),(X),88269,(X),52.1,2,47.9,2
197,1600000US0908000,"Bridgeport city, Connecticut",148365,48,74360,2521,74005,2521,100.5,6.8,...,1.8,0.9,(X),(X),95393,(X),47.9,2.3,52.1,2.3
198,1600000US0918430,"Danbury city, Connecticut",86971,33,44757,1971,42214,1968,106,9.5,...,3.6,2.6,(X),(X),52706,(X),50.8,2.8,49.2,2.8
199,1600000US0937000,"Hartford city, Connecticut",120682,37,60090,2762,60592,2761,99.2,9.1,...,2.6,1,(X),(X),78626,(X),46.5,2.5,53.5,2.5

In [61]:
population2_df.head

<bound method NDFrame.head of                GEO_ID                               NAME  \
0           Geography               Geographic Area Name
1    1600000US0103076               Auburn city, Alabama
2    1600000US0107000           Birmingham city, Alabama
3    1600000US0121184               Dothan city, Alabama
4    1600000US0135896               Hoover city, Alabama
..                ...                                ...
642  1600000US7210334    Caguas zona urbana, Puerto Rico
643  1600000US7214290  Carolina zona urbana, Puerto Rico
644  1600000US7232522  Guaynabo zona urbana, Puerto Rico
645  1600000US7263820     Ponce zona urbana, Puerto Rico
646  1600000US7276770  San Juan zona urbana, Puerto Rico

                                  DP05_0001E  \
0    Estimate!!SEX AND AGE!!Total population
1                                      80009
2                                     196353
3                                      70524
4                                      92427
..                                       ...
642                                    68451
643                                   134842
644                                    70174
645                                   105979
646                                   319837

                                         DP05_0001M  \
0    Margin of Error!!SEX AND AGE!!Total population
1                                                20
2                                               868
3                                               678
4                                                45
..                                              ...
642                                            4611
643                                            3835
644                                            2891
645                                            3615
646                                            3038

                                        DP05_0002E  \
0    Estimate!!SEX AND AGE!!Total population!!Male
1                                            39138
2                                            91868
3                                            33526
4                                            44454
..                                             ...
642                                          31344
643                                          60801
644                                          31710
645                                          48160
646                                         145595

                                            DP05_0002M  \
0    Margin of Error!!SEX AND AGE!!Total population...
1                                                 1579
2                                                 2302
3                                                  969
4                                                 2273
..                                                 ...
642                                               2487
643                                               2060
644                                               1693
645                                               2021
646                                               1582

                                          DP05_0003E  \
0    Estimate!!SEX AND AGE!!Total population!!Female
1                                              40871
2                                             104485
3                                              36998
4                                              47973
..                                               ...
642                                            37107
643                                            74041
644                                            38464
645                                            57819
646                                           174242

                                            DP05_0003M  \
0    Margin of Error!!SEX AND AGE!!Total population...
1                                                 1582
2                                                 2421
3                                                  913
4                                                 2274
..                                                 ...
642                                               3101
643                                               2144
644                                               1814
645                                               2164
646                                               1935

                                            DP05_0004E  \
0    Estimate!!SEX AND AGE!!Total population!!Sex r...
1                                                 95.8
2                                                 87.9
3                                                 90.6
4                                                 92.7
..                                                 ...
642                                               84.5
643                                               82.1
644                                               82.4
645                                               83.3
646                                               83.6

                                            DP05_0004M  ...  \
0    Margin of Error!!SEX AND AGE!!Total population...  ...
1                                                  7.6  ...
2                                                  4.2  ...
3                                                  4.5  ...
4                                                  9.1  ...
..                                                 ...  ...
642                                                7.8  ...
643                                                2.2  ...
644                                                4.7  ...
645                                                3.3  ...
646                                                0.9  ...

                                           DP05_0087PE  \
0    Percent!!HISPANIC OR LATINO AND RACE!!Total po...
1                                                  3.1
2                                                    1
3                                                  2.7
4                                                  1.2
..                                                 ...
642                                                  N
643                                                  N
644                                                  N
645                                                  N
646                                                0.3

                                           DP05_0087PM  \
0    Percent Margin of Error!!HISPANIC OR LATINO AN...
1                                                  1.7
2                                                  0.4
3                                                  0.9
4                                                  0.8
..                                                 ...
642                                                  N
643                                                  N
644                                                  N
645                                                  N
646                                                0.4

                      DP05_0088PE  \
0    Percent!!Total housing units
1                             (X)
2                             (X)
3                             (X)
4                             (X)
..                            ...
642                           (X)
643                           (X)
644                           (X)
645                           (X)
646                           (X)

                                      DP05_0088PM  \
0    Percent Margin of Error!!Total housing units
1                                             (X)
2                                             (X)
3                                             (X)
4                                             (X)
..                                            ...
642                                           (X)
643                                           (X)
644                                           (X)
645                                           (X)
646                                           (X)

                                           DP05_0089PE  \
0    Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
1                                                60600
2                                               152283
3                                                52848
4                                                66535
..                                                 ...
642                                              58008
643                                             109386
644                                              58225
645                                              87195
646                                             256634

                                           DP05_0089PM  \
0    Percent Margin of Error!!CITIZEN, VOTING AGE P...
1                                                  (X)
2                                                  (X)
3                                                  (X)
4                                                  (X)
..                                                 ...
642                                                (X)
643                                                (X)
644                                                (X)
645                                                (X)
646                                                (X)

                                           DP05_0090PE  \
0    Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
1                                                 48.5
2                                                   45
3                                                   46
4                                                 45.4
..                                                 ...
642                                                 43
643                                               44.1
644                                               45.5
645                                               44.4
646                                               44.5

                                           DP05_0090PM  \
0    Percent Margin of Error!!CITIZEN, VOTING AGE P...
1                                                  2.3
2                                                  1.3
3                                                  1.3
4                                                  2.9
..                                                 ...
642                                                2.5
643                                                  1
644                                                1.5
645                                                1.1
646                                                0.5

                                           DP05_0091PE  \
0    Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
1                                                 51.5
2                                                   55
3                                                   54
4                                                 54.6
..                                                 ...
642                                                 57
643                                               55.9
644                                               54.5
645                                               55.6
646                                               55.5

                                           DP05_0091PM
0    Percent Margin of Error!!CITIZEN, VOTING AGE P...
1                                                  2.3
2                                                  1.3
3                                                  1.3
4                                                  2.9
..                                                 ...
642                                                2.5
643                                                  1
644                                                1.5
645                                                1.1
646                                                0.5

[647 rows x 366 columns]>

In [62]:
population2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 647 entries, 0 to 646
Columns: 366 entries, GEO_ID to DP05_0091PM
dtypes: object(366)
memory usage: 1.8+ MB

In [63]:
population2_df.columns

Index(['GEO_ID', 'NAME', 'DP05_0001E', 'DP05_0001M', 'DP05_0002E',
       'DP05_0002M', 'DP05_0003E', 'DP05_0003M', 'DP05_0004E', 'DP05_0004M',
       ...
       'DP05_0087PE', 'DP05_0087PM', 'DP05_0088PE', 'DP05_0088PM',
       'DP05_0089PE', 'DP05_0089PM', 'DP05_0090PE', 'DP05_0090PM',
       'DP05_0091PE', 'DP05_0091PM'],
      dtype='object', length=366)

In [64]:
population2_df.drop (columns=['GEO_ID', 'DP05_0001M', 'DP05_0002E',
       'DP05_0002M', 'DP05_0003E', 'DP05_0003M', 'DP05_0004E', 'DP05_0004M',
       'DP05_0087PE', 'DP05_0087PM', 'DP05_0088PE', 'DP05_0088PM',
       'DP05_0089PE', 'DP05_0089PM', 'DP05_0090PE', 'DP05_0090PM',
       'DP05_0091PE', 'DP05_0091PM',
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0005E,DP05_0005M,DP05_0006E,DP05_0006M,DP05_0007E,DP05_0007M,DP05_0008E,DP05_0008M,...,DP05_0082PE,DP05_0082PM,DP05_0083PE,DP05_0083PM,DP05_0084PE,DP05_0084PM,DP05_0085PE,DP05_0085PM,DP05_0086PE,DP05_0086PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Under...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!5 to ...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!10 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!15 to...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...
1,"Auburn city, Alabama",80009,3657,1311,3809,1134,4348,1136,10742,1267,...,8.6,1.2,0,0.2,1.1,1.4,3.3,1.7,0.2,0.3
2,"Birmingham city, Alabama",196353,11495,2020,11631,2173,9404,2476,12569,1638,...,1.8,0.8,0,0.1,0.8,0.5,1.3,0.5,0.3,0.3
3,"Dothan city, Alabama",70524,4549,468,5059,662,4146,592,3971,660,...,1.3,0.4,0,0.3,0.1,0.1,3.6,1,0.8,0.6
4,"Hoover city, Alabama",92427,5778,1406,5805,1516,7377,2051,4891,1141,...,4.8,1.7,0,0.2,0,0.2,1.2,0.8,0.1,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,9148,1984,8030,1658,11235,2029,10654,1951,...,6,1.7,0,0.1,0.4,0.3,3.1,1.1,0.4,0.3
196,"Westminster city, Colorado",114539,6111,1433,5566,1489,6461,1771,6248,1452,...,7,2.1,0.1,0.1,0.8,0.7,3.6,1.1,0.5,0.3
197,"Bridgeport city, Connecticut",148365,7257,1287,6538,1438,10997,2138,10543,1639,...,4.9,1.3,0,0.1,2.6,1.8,6.6,2.5,4.9,2.4
198,"Danbury city, Connecticut",86971,4478,1399,6422,2246,5191,1501,7885,1525,...,2.9,1.3,0,0.2,4.5,2.6,10.2,3.6,6.7,2.3
199,"Hartford city, Connecticut",120682,6924,2104,7297,2023,7948,1900,8488,1729,...,3.1,1.1,0,0.2,0.4,0.3,2.7,1,0.1,0.1

In [65]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0005E', 'DP05_0005M', 'DP05_0006E',
       'DP05_0006M', 'DP05_0007E', 'DP05_0007M', 'DP05_0008E', 'DP05_0008M',
       ...
       'DP05_0082PE', 'DP05_0082PM', 'DP05_0083PE', 'DP05_0083PM',
       'DP05_0084PE', 'DP05_0084PM', 'DP05_0085PE', 'DP05_0085PM',
       'DP05_0086PE', 'DP05_0086PM'],
      dtype='object', length=348)

In [66]:
population2_df.drop (columns=['DP05_0005E', 'DP05_0005M', 'DP05_0006E',
       'DP05_0006M', 'DP05_0007E', 'DP05_0007M', 'DP05_0008E', 'DP05_0008M',
       'DP05_0082PE', 'DP05_0082PM', 'DP05_0083PE', 'DP05_0083PM',
       'DP05_0084PE', 'DP05_0084PM', 'DP05_0085PE', 'DP05_0085PM',
       'DP05_0086PE', 'DP05_0086PM',
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0009E,DP05_0009M,DP05_0010E,DP05_0010M,DP05_0011E,DP05_0011M,DP05_0012E,DP05_0012M,...,DP05_0077PE,DP05_0077PM,DP05_0078PE,DP05_0078PM,DP05_0079PE,DP05_0079PM,DP05_0080PE,DP05_0080PM,DP05_0081PE,DP05_0081PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!20 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!25 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!35 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!45 to...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...
1,"Auburn city, Alabama",80009,17844,1977,9951,1626,8885,1338,8264,1452,...,2.2,1.1,95,1.6,67.8,3.6,14.2,3.7,0,0.2
2,"Birmingham city, Alabama",196353,17080,2690,35456,3273,22031,2235,21138,2406,...,1.3,0.7,96.9,1.1,21.9,1.9,71,2.4,0.1,0.1
3,"Dothan city, Alabama",70524,4274,540,10025,734,8299,857,7966,676,...,1.5,0.8,95.3,0.6,57.6,2,32.5,1.8,0.2,0.2
4,"Hoover city, Alabama",92427,6165,1699,8728,2068,12512,2245,12198,1983,...,N,N,94.1,2.5,72.8,4,15.2,4.1,0,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,10917,2218,21199,3198,23457,2647,18629,2478,...,5.8,2.4,60.3,4.3,48.5,3.7,2,0.9,0.3,0.2
196,"Westminster city, Colorado",114539,5971,1990,22450,2873,19313,2544,15127,2135,...,5.5,2,78.8,3.5,64.6,3.7,1.4,0.8,1.3,1
197,"Bridgeport city, Connecticut",148365,11662,2101,20230,1840,21169,1759,16098,1957,...,14.7,2.8,62.5,2.1,28.6,3.5,19.7,2.1,0.2,0.2
198,"Danbury city, Connecticut",86971,5404,1255,13431,2147,10014,1700,10756,2158,...,25.9,5.7,66.6,5.4,37,4.7,11.9,3.3,0,0.1
199,"Hartford city, Connecticut",120682,13791,2416,20275,2597,14191,2034,14442,2280,...,14.1,4,55.2,3.9,16.4,2.5,32.5,4.4,0.1,0.2

In [67]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0009E', 'DP05_0009M', 'DP05_0010E',
       'DP05_0010M', 'DP05_0011E', 'DP05_0011M', 'DP05_0012E', 'DP05_0012M',
       ...
       'DP05_0077PE', 'DP05_0077PM', 'DP05_0078PE', 'DP05_0078PM',
       'DP05_0079PE', 'DP05_0079PM', 'DP05_0080PE', 'DP05_0080PM',
       'DP05_0081PE', 'DP05_0081PM'],
      dtype='object', length=330)

In [68]:
population2_df.drop (columns=['DP05_0009E', 'DP05_0009M', 'DP05_0010E',
       'DP05_0010M', 'DP05_0011E', 'DP05_0011M', 'DP05_0012E', 'DP05_0012M',
       'DP05_0077PE', 'DP05_0077PM', 'DP05_0078PE', 'DP05_0078PM',
       'DP05_0079PE', 'DP05_0079PM', 'DP05_0080PE', 'DP05_0080PM',
       'DP05_0081PE', 'DP05_0081PM',
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0013E,DP05_0013M,DP05_0014E,DP05_0014M,DP05_0015E,DP05_0015M,DP05_0016E,DP05_0016M,...,DP05_0072PE,DP05_0072PM,DP05_0073PE,DP05_0073PM,DP05_0074PE,DP05_0074PM,DP05_0075PE,DP05_0075PM,DP05_0076PE,DP05_0076PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!55 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!60 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!65 to...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!75 to...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...
1,"Auburn city, Alabama",80009,2952,986,3017,854,3809,1040,2251,699,...,80009,(X),5,1.6,2.3,1.7,0.2,0.3,0.3,0.3
2,"Birmingham city, Alabama",196353,11701,1930,13034,1803,19838,1905,7448,1209,...,196353,(X),3.1,1.1,1.6,0.8,0.1,0.1,0.1,0.1
3,"Dothan city, Alabama",70524,4307,538,4464,600,8159,546,3994,586,...,70524,(X),4.7,0.6,2.3,1,0.8,0.5,0.2,0.2
4,"Hoover city, Alabama",92427,4066,1060,7264,1533,9138,1812,5231,1277,...,92427,(X),5.9,2.5,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,6964,1784,6798,1705,11471,1838,4129,1141,...,143279,(X),39.7,4.3,33.5,4.5,0.5,0.4,0,0.1
196,"Westminster city, Colorado",114539,5914,1313,5034,1279,10216,1414,4625,1069,...,114539,(X),21.2,3.5,15.4,3.4,0.4,0.3,0,0.2
197,"Bridgeport city, Connecticut",148365,10214,2234,11103,1759,12835,1543,7803,1820,...,148365,(X),37.5,2.1,4.2,2.1,16.1,2.6,2.5,2.2
198,"Danbury city, Connecticut",86971,6294,1691,4235,1592,8087,1898,3225,987,...,86971,(X),33.4,5.4,3.9,2.1,3.4,1.9,0.3,0.3
199,"Hartford city, Connecticut",120682,8204,1494,4313,1191,8841,1498,4393,940,...,120682,(X),44.8,3.9,2.1,1.5,27.6,3.8,1,0.8

In [69]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0013E', 'DP05_0013M', 'DP05_0014E',
       'DP05_0014M', 'DP05_0015E', 'DP05_0015M', 'DP05_0016E', 'DP05_0016M',
       ...
       'DP05_0072PE', 'DP05_0072PM', 'DP05_0073PE', 'DP05_0073PM',
       'DP05_0074PE', 'DP05_0074PM', 'DP05_0075PE', 'DP05_0075PM',
       'DP05_0076PE', 'DP05_0076PM'],
      dtype='object', length=312)

In [70]:
population2_df.drop (columns=['DP05_0013E', 'DP05_0013M', 'DP05_0014E',
       'DP05_0014M', 'DP05_0015E', 'DP05_0015M', 'DP05_0016E', 'DP05_0016M',
       'DP05_0072PE', 'DP05_0072PM', 'DP05_0073PE', 'DP05_0073PM',
       'DP05_0074PE', 'DP05_0074PM', 'DP05_0075PE', 'DP05_0075PM',
       'DP05_0076PE', 'DP05_0076PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0017E,DP05_0017M,DP05_0018E,DP05_0018M,DP05_0019E,DP05_0019M,DP05_0020E,DP05_0020M,...,DP05_0067PE,DP05_0067PM,DP05_0068PE,DP05_0068PM,DP05_0069PE,DP05_0069PM,DP05_0070PE,DP05_0070PM,DP05_0071PE,DP05_0071PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!85 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Media...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Under...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!16 ye...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...
1,"Auburn city, Alabama",80009,480,308,24.7,1.4,14785,1969,67688,1889,...,16.1,3.5,1.1,1,11.1,1.8,N,N,5.2,2.4
2,"Birmingham city, Alabama",196353,3528,821,35.2,1.3,38085,3305,162122,3254,...,71.7,2.4,0.4,0.2,2.1,0.7,0.3,0.2,3.5,1.1
3,"Dothan city, Alabama",70524,1311,320,38.7,1.5,16226,976,55903,1021,...,34.5,1.9,1.6,0.6,1.8,0.5,0.4,0.3,3.8,1
4,"Hoover city, Alabama",92427,3274,1316,40.7,3.7,22682,3051,72341,3049,...,16.5,4.3,1.6,1.3,5.2,1.7,N,N,4,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,648,403,35.2,1.7,35739,3477,112681,3514,...,4.3,2.1,2.6,1,8.1,1.8,N,N,26.8,5.2
196,"Westminster city, Colorado",114539,1503,735,37.1,1.6,21066,2827,95525,2774,...,3.3,1.2,2.8,1.1,8.6,2.2,N,N,16.1,3.1
197,"Bridgeport city, Connecticut",148365,1916,762,38,1.6,30387,2638,121458,2769,...,27.9,3.2,1.3,0.8,5.4,1.3,N,N,36.7,4.3
198,"Danbury city, Connecticut",86971,1549,557,35.6,3.4,19979,2935,69942,2862,...,19.4,4.5,0.9,0.6,3.1,1.3,0.1,0.1,41.8,5.6
199,"Hartford city, Connecticut",120682,1575,602,32.4,0.9,25540,2710,96632,2801,...,43.1,4.8,2.4,1.2,4.1,1.4,N,N,27.5,4.1

In [71]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0017E', 'DP05_0017M', 'DP05_0018E',
       'DP05_0018M', 'DP05_0019E', 'DP05_0019M', 'DP05_0020E', 'DP05_0020M',
       ...
       'DP05_0067PE', 'DP05_0067PM', 'DP05_0068PE', 'DP05_0068PM',
       'DP05_0069PE', 'DP05_0069PM', 'DP05_0070PE', 'DP05_0070PM',
       'DP05_0071PE', 'DP05_0071PM'],
      dtype='object', length=294)

In [72]:
population2_df.drop (columns=['DP05_0017E', 'DP05_0017M', 'DP05_0018E',
       'DP05_0018M', 'DP05_0019E', 'DP05_0019M', 'DP05_0020E', 'DP05_0020M',
       'DP05_0067PE', 'DP05_0067PM', 'DP05_0068PE', 'DP05_0068PM',
       'DP05_0069PE', 'DP05_0069PM', 'DP05_0070PE', 'DP05_0070PM',
       'DP05_0071PE', 'DP05_0071PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0021E,DP05_0021M,DP05_0022E,DP05_0022M,DP05_0023E,DP05_0023M,DP05_0024E,DP05_0024M,...,DP05_0062PE,DP05_0062PM,DP05_0063PE,DP05_0063PM,DP05_0064PE,DP05_0064PM,DP05_0065PE,DP05_0065PM,DP05_0066PE,DP05_0066PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!18 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!21 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!62 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...,Percent!!Race alone or in combination with one...,Percent Margin of Error!!Race alone or in comb...
1,"Auburn city, Alabama",80009,65224,1967,51303,2475,7866,1470,6540,1327,...,1.3,1,0,0.2,0,0.2,80009,(X),73.4,4.1
2,"Birmingham city, Alabama",196353,158268,3252,147804,3329,39333,2660,30814,2237,...,1.1,0.5,0,0.1,0.1,0.1,196353,(X),24.3,1.9
3,"Dothan city, Alabama",70524,54298,1035,51713,1088,16019,911,13464,726,...,2.4,0.9,0.4,0.4,0.1,0.2,70524,(X),63.8,2
4,"Hoover city, Alabama",92427,69745,3053,66307,3200,21656,2914,17643,2539,...,N,N,N,N,N,N,92427,(X),77.9,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,107540,3481,101868,3598,20735,2724,16248,2174,...,14.2,3.7,0,0.1,0,0.1,143279,(X),77.2,3.9
196,"Westminster city, Colorado",114539,93473,2833,89362,2575,19011,2307,16344,2020,...,10.5,2.8,0,0.2,0.1,0.2,114539,(X),84.9,3.1
197,"Bridgeport city, Connecticut",148365,117978,2635,110940,2751,28497,3149,22554,2831,...,11.3,3.1,0.7,0.6,4.1,2.2,148365,(X),47.7,4
198,"Danbury city, Connecticut",86971,66992,2940,60964,3249,15625,3141,12861,2603,...,15.8,4.6,0.4,0.5,2.9,1.8,86971,(X),59.6,5.7
199,"Hartford city, Connecticut",120682,95142,2709,86242,2859,17643,2167,14809,1887,...,3.5,1.5,1.1,1,0.3,0.3,120682,(X),36.9,4.5

In [73]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0021E', 'DP05_0021M', 'DP05_0022E',
       'DP05_0022M', 'DP05_0023E', 'DP05_0023M', 'DP05_0024E', 'DP05_0024M',
       ...
       'DP05_0062PE', 'DP05_0062PM', 'DP05_0063PE', 'DP05_0063PM',
       'DP05_0064PE', 'DP05_0064PM', 'DP05_0065PE', 'DP05_0065PM',
       'DP05_0066PE', 'DP05_0066PM'],
      dtype='object', length=276)

In [74]:
population2_df.drop (columns=['DP05_0021E', 'DP05_0021M', 'DP05_0022E',
       'DP05_0022M', 'DP05_0023E', 'DP05_0023M', 'DP05_0024E', 'DP05_0024M',
       'DP05_0062PE', 'DP05_0062PM', 'DP05_0063PE', 'DP05_0063PM',
       'DP05_0064PE', 'DP05_0064PM', 'DP05_0065PE', 'DP05_0065PM',
       'DP05_0066PE', 'DP05_0066PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0025E,DP05_0025M,DP05_0026E,DP05_0026M,DP05_0027E,DP05_0027M,DP05_0028E,DP05_0028M,...,DP05_0057PE,DP05_0057PM,DP05_0058PE,DP05_0058PM,DP05_0059PE,DP05_0059PM,DP05_0060PE,DP05_0060PM,DP05_0061PE,DP05_0061PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!18 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!18 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!18 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!18 ye...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!RACE!!Total population!!One race!!Som...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...
1,"Auburn city, Alabama",80009,65224,1967,32193,1716,33031,1444,97.5,7.5,...,3.2,2.1,4.9,2.2,0.6,0.6,0.4,0.4,0.8,0.8
2,"Birmingham city, Alabama",196353,158268,3252,72395,2646,85873,2557,84.3,4.4,...,2.3,1,2.2,0.6,0.4,0.3,0.2,0.1,0,0.1
3,"Dothan city, Alabama",70524,54298,1035,25164,927,29134,791,86.4,4.5,...,1.2,0.7,5.5,1.3,1.1,0.7,0.7,0.2,0.2,0.1
4,"Hoover city, Alabama",92427,69745,3053,32083,2288,37662,2607,85.2,9.4,...,0.4,0.4,4.8,2.3,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,107540,3481,51313,2648,56227,2067,91.3,5.6,...,11.8,4,18.4,3.8,0.6,0.5,1,0.5,1.6,0.7
196,"Westminster city, Colorado",114539,93473,2833,48677,2663,44796,1813,108.7,8.2,...,4.6,2.2,14.9,2.7,1.3,0.6,0.7,0.4,1.2,0.6
197,"Bridgeport city, Connecticut",148365,117978,2635,58826,2538,59152,2384,99.4,7,...,20.2,4.3,18.2,3.7,0.1,0.2,0,0.1,0.4,0.5
198,"Danbury city, Connecticut",86971,66992,2940,33763,2296,33229,2007,101.6,9.5,...,21.5,6.2,23.3,5.3,2.1,1.6,0.2,0.2,0.1,0.2
199,"Hartford city, Connecticut",120682,95142,2709,46154,3005,48988,2374,94.2,9.3,...,22.4,4.2,13.2,2.9,6,2.2,0.3,0.2,0.4,0.3

In [75]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0025E', 'DP05_0025M', 'DP05_0026E',
       'DP05_0026M', 'DP05_0027E', 'DP05_0027M', 'DP05_0028E', 'DP05_0028M',
       ...
       'DP05_0057PE', 'DP05_0057PM', 'DP05_0058PE', 'DP05_0058PM',
       'DP05_0059PE', 'DP05_0059PM', 'DP05_0060PE', 'DP05_0060PM',
       'DP05_0061PE', 'DP05_0061PM'],
      dtype='object', length=258)

In [76]:
population2_df.drop (columns=['DP05_0025E', 'DP05_0025M', 'DP05_0026E',
       'DP05_0026M', 'DP05_0027E', 'DP05_0027M', 'DP05_0028E', 'DP05_0028M',
       'DP05_0057PE', 'DP05_0057PM', 'DP05_0058PE', 'DP05_0058PM',
       'DP05_0059PE', 'DP05_0059PM', 'DP05_0060PE', 'DP05_0060PM',
       'DP05_0061PE', 'DP05_0061PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0029E,DP05_0029M,DP05_0030E,DP05_0030M,DP05_0031E,DP05_0031M,DP05_0032E,DP05_0032M,...,DP05_0052PE,DP05_0052PM,DP05_0053PE,DP05_0053PM,DP05_0054PE,DP05_0054PM,DP05_0055PE,DP05_0055PM,DP05_0056PE,DP05_0056PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!RACE!!Total population!!One race!!Nat...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Nat...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Nat...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Nat...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Nat...,Percent Margin of Error!!RACE!!Total populatio...
1,"Auburn city, Alabama",80009,6540,1327,2969,735,3571,893,83.1,24.1,...,0,0.2,N,N,N,N,N,N,N,N
2,"Birmingham city, Alabama",196353,30814,2237,12327,1270,18487,1464,66.7,7.1,...,0,0.1,N,N,N,N,N,N,N,N
3,"Dothan city, Alabama",70524,13464,726,5560,484,7904,462,70.3,6.8,...,0,0.3,N,N,N,N,N,N,N,N
4,"Hoover city, Alabama",92427,17643,2539,7192,1321,10451,1742,68.8,13.5,...,0,0.2,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,16248,2174,7013,1261,9235,1253,75.9,12.4,...,0,0.1,N,N,N,N,N,N,N,N
196,"Westminster city, Colorado",114539,16344,2020,7467,1131,8877,1283,84.1,13.5,...,0.1,0.1,N,N,N,N,N,N,N,N
197,"Bridgeport city, Connecticut",148365,22554,2831,10982,1622,11572,1715,94.9,15.1,...,0,0.1,N,N,N,N,N,N,N,N
198,"Danbury city, Connecticut",86971,12861,2603,6259,1485,6602,1482,94.8,21.1,...,0.1,0.1,N,N,N,N,N,N,N,N
199,"Hartford city, Connecticut",120682,14809,1887,5734,1095,9075,1298,63.2,13.3,...,0,0.2,N,N,N,N,N,N,N,N

In [77]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0029E', 'DP05_0029M', 'DP05_0030E',
       'DP05_0030M', 'DP05_0031E', 'DP05_0031M', 'DP05_0032E', 'DP05_0032M',
       ...
       'DP05_0052PE', 'DP05_0052PM', 'DP05_0053PE', 'DP05_0053PM',
       'DP05_0054PE', 'DP05_0054PM', 'DP05_0055PE', 'DP05_0055PM',
       'DP05_0056PE', 'DP05_0056PM'],
      dtype='object', length=240)

In [78]:
population2_df.drop (columns=['DP05_0029E', 'DP05_0029M', 'DP05_0030E',
       'DP05_0030M', 'DP05_0031E', 'DP05_0031M', 'DP05_0032E', 'DP05_0032M',
       'DP05_0052PE', 'DP05_0052PM', 'DP05_0053PE', 'DP05_0053PM',
       'DP05_0054PE', 'DP05_0054PM', 'DP05_0055PE', 'DP05_0055PM',
       'DP05_0056PE', 'DP05_0056PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0033E,DP05_0033M,DP05_0034E,DP05_0034M,DP05_0035E,DP05_0035M,DP05_0036E,DP05_0036M,...,DP05_0047PE,DP05_0047PM,DP05_0048PE,DP05_0048PM,DP05_0049PE,DP05_0049PM,DP05_0050PE,DP05_0050PM,DP05_0051PE,DP05_0051PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Margin of Error!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,Estimate!!RACE!!Total population!!One race,Margin of Error!!RACE!!Total population!!One race,...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...
1,"Auburn city, Alabama",80009,80009,20,76060,1785,3949,1782,76060,1785,...,0.2,0.3,0.1,0.2,3.8,1.5,0.5,0.6,1.2,0.9
2,"Birmingham city, Alabama",196353,196353,868,191945,1409,4408,1206,191945,1409,...,N,N,N,N,N,N,N,N,N,N
3,"Dothan city, Alabama",70524,70524,678,66638,1095,3886,910,66638,1095,...,N,N,N,N,N,N,N,N,N,N
4,"Hoover city, Alabama",92427,92427,45,87948,2104,4479,2099,87948,2104,...,N,N,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,143279,38,116925,5489,26354,5484,116925,5489,...,0.9,0.6,0.1,0.1,0.5,0.4,0.6,0.5,2.9,1.8
196,"Westminster city, Colorado",114539,114539,39,97420,3139,17119,3139,97420,3139,...,0.4,0.4,0.4,0.3,0.9,0.5,0.8,0.7,2.9,1.4
197,"Bridgeport city, Connecticut",148365,148365,48,121429,5440,26936,5434,121429,5440,...,N,N,N,N,N,N,N,N,N,N
198,"Danbury city, Connecticut",86971,86971,33,66707,4648,20264,4645,66707,4648,...,N,N,N,N,N,N,N,N,N,N
199,"Hartford city, Connecticut",120682,120682,37,104806,3499,15876,3498,104806,3499,...,0,0.1,0,0.2,0,0.2,1,0.8,0.4,0.4

In [79]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0033E', 'DP05_0033M', 'DP05_0034E',
       'DP05_0034M', 'DP05_0035E', 'DP05_0035M', 'DP05_0036E', 'DP05_0036M',
       ...
       'DP05_0047PE', 'DP05_0047PM', 'DP05_0048PE', 'DP05_0048PM',
       'DP05_0049PE', 'DP05_0049PM', 'DP05_0050PE', 'DP05_0050PM',
       'DP05_0051PE', 'DP05_0051PM'],
      dtype='object', length=222)

In [80]:
population2_df.drop (columns=['DP05_0033E', 'DP05_0033M', 'DP05_0034E',
       'DP05_0034M', 'DP05_0035E', 'DP05_0035M', 'DP05_0036E', 'DP05_0036M',
       'DP05_0047PE', 'DP05_0047PM', 'DP05_0048PE', 'DP05_0048PM',
       'DP05_0049PE', 'DP05_0049PM', 'DP05_0050PE', 'DP05_0050PM',
       'DP05_0051PE', 'DP05_0051PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0037E,DP05_0037M,DP05_0038E,DP05_0038M,DP05_0039E,DP05_0039M,DP05_0040E,DP05_0040M,...,DP05_0042PE,DP05_0042PM,DP05_0043PE,DP05_0043PM,DP05_0044PE,DP05_0044PM,DP05_0045PE,DP05_0045PM,DP05_0046PE,DP05_0046PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!One race!!White,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Bl...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Am...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Am...,Margin of Error!!RACE!!Total population!!One r...,...,Percent!!RACE!!Total population!!One race!!Ame...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Ame...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asian,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Asi...,Percent Margin of Error!!RACE!!Total populatio...
1,"Auburn city, Alabama",80009,55040,2985,11489,3014,118,152,N,N,...,N,N,N,N,8.6,1.2,1.6,1.1,1.2,1.1
2,"Birmingham city, Alabama",196353,43953,3859,139595,4683,181,158,N,N,...,N,N,N,N,1.9,0.8,N,N,N,N
3,"Dothan city, Alabama",70524,41639,1545,22927,1320,285,237,N,N,...,N,N,N,N,1.3,0.4,N,N,N,N
4,"Hoover city, Alabama",92427,68014,3743,14330,3790,788,1217,N,N,...,N,N,N,N,4.8,1.7,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,84962,6580,5005,2886,1287,809,N,N,...,N,N,N,N,6.2,1.7,0.5,0.4,0.8,0.4
196,"Westminster city, Colorado",114539,80580,4072,1809,981,1441,1112,N,N,...,N,N,N,N,7.2,2.1,1,0.8,0.7,0.6
197,"Bridgeport city, Connecticut",148365,51703,5923,32184,3463,418,371,N,N,...,N,N,N,N,4.9,1.3,N,N,N,N
198,"Danbury city, Connecticut",86971,34614,4089,10729,2881,12,7,N,N,...,N,N,N,N,2.9,1.3,N,N,N,N
199,"Hartford city, Connecticut",120682,31218,4519,41834,5452,424,471,N,N,...,N,N,N,N,3.5,1.3,0.8,0.6,1.3,0.8

In [81]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0037E', 'DP05_0037M', 'DP05_0038E',
       'DP05_0038M', 'DP05_0039E', 'DP05_0039M', 'DP05_0040E', 'DP05_0040M',
       ...
       'DP05_0042PE', 'DP05_0042PM', 'DP05_0043PE', 'DP05_0043PM',
       'DP05_0044PE', 'DP05_0044PM', 'DP05_0045PE', 'DP05_0045PM',
       'DP05_0046PE', 'DP05_0046PM'],
      dtype='object', length=204)

In [82]:
population2_df.drop (columns=['DP05_0037E', 'DP05_0037M', 'DP05_0038E',
       'DP05_0038M', 'DP05_0039E', 'DP05_0039M', 'DP05_0040E', 'DP05_0040M',
       'DP05_0042PE', 'DP05_0042PM', 'DP05_0043PE', 'DP05_0043PM',
       'DP05_0044PE', 'DP05_0044PM', 'DP05_0045PE', 'DP05_0045PM',
       'DP05_0046PE', 'DP05_0046PM'
    
], inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0041E,DP05_0041M,DP05_0042E,DP05_0042M,DP05_0043E,DP05_0043M,DP05_0044E,DP05_0044M,...,DP05_0037PE,DP05_0037PM,DP05_0038PE,DP05_0038PM,DP05_0039PE,DP05_0039PM,DP05_0040PE,DP05_0040PM,DP05_0041PE,DP05_0041PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!One race!!Am...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Am...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Am...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Asian,Margin of Error!!RACE!!Total population!!One r...,...,Percent!!RACE!!Total population!!One race!!White,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Bla...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Ame...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Ame...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race!!Ame...,Percent Margin of Error!!RACE!!Total populatio...
1,"Auburn city, Alabama",80009,N,N,N,N,N,N,6892,996,...,68.8,3.7,14.4,3.8,0.1,0.2,N,N,N,N
2,"Birmingham city, Alabama",196353,N,N,N,N,N,N,3644,1539,...,22.4,2,71.1,2.4,0.1,0.1,N,N,N,N
3,"Dothan city, Alabama",70524,N,N,N,N,N,N,912,284,...,59,2.1,32.5,1.8,0.4,0.3,N,N,N,N
4,"Hoover city, Alabama",92427,N,N,N,N,N,N,4444,1570,...,73.6,4,15.5,4.1,0.9,1.3,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,N,N,N,N,N,N,8815,2384,...,59.3,4.6,3.5,2,0.9,0.6,N,N,N,N
196,"Westminster city, Colorado",114539,N,N,N,N,N,N,8235,2381,...,70.4,3.6,1.6,0.9,1.3,1,N,N,N,N
197,"Bridgeport city, Connecticut",148365,N,N,N,N,N,N,7198,1857,...,34.8,4,21.7,2.3,0.3,0.3,N,N,N,N
198,"Danbury city, Connecticut",86971,N,N,N,N,N,N,2516,1119,...,39.8,4.7,12.3,3.3,0,0.1,N,N,N,N
199,"Hartford city, Connecticut",120682,N,N,N,N,N,N,4279,1531,...,25.9,3.7,34.7,4.5,0.4,0.4,N,N,N,N

In [83]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0041E', 'DP05_0041M', 'DP05_0042E',
       'DP05_0042M', 'DP05_0043E', 'DP05_0043M', 'DP05_0044E', 'DP05_0044M',
       ...
       'DP05_0037PE', 'DP05_0037PM', 'DP05_0038PE', 'DP05_0038PM',
       'DP05_0039PE', 'DP05_0039PM', 'DP05_0040PE', 'DP05_0040PM',
       'DP05_0041PE', 'DP05_0041PM'],
      dtype='object', length=186)

In [84]:
population2_df.drop (columns=['DP05_0041E', 'DP05_0041M', 'DP05_0042E',
       'DP05_0042M', 'DP05_0043E', 'DP05_0043M', 'DP05_0044E', 'DP05_0044M',
       'DP05_0037PE', 'DP05_0037PM', 'DP05_0038PE', 'DP05_0038PM',
       'DP05_0039PE', 'DP05_0039PM', 'DP05_0040PE', 'DP05_0040PM',
       'DP05_0041PE', 'DP05_0041PM']
    
, inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0045E,DP05_0045M,DP05_0046E,DP05_0046M,DP05_0047E,DP05_0047M,DP05_0048E,DP05_0048M,...,DP05_0032PE,DP05_0032PM,DP05_0033PE,DP05_0033PM,DP05_0034PE,DP05_0034PM,DP05_0035PE,DP05_0035PM,DP05_0036PE,DP05_0036PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,...,Percent!!SEX AND AGE!!Total population!!65 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!RACE!!Total population,Percent Margin of Error!!RACE!!Total population,Percent!!RACE!!Total population!!One race,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!Two or More R...,Percent Margin of Error!!RACE!!Total populatio...,Percent!!RACE!!Total population!!One race,Percent Margin of Error!!RACE!!Total populatio...
1,"Auburn city, Alabama",80009,1267,905,932,897,172,264,85,141,...,(X),(X),80009,(X),95.1,2.2,4.9,2.2,95.1,2.2
2,"Birmingham city, Alabama",196353,N,N,N,N,N,N,N,N,...,(X),(X),196353,(X),97.8,0.6,2.2,0.6,97.8,0.6
3,"Dothan city, Alabama",70524,N,N,N,N,N,N,N,N,...,(X),(X),70524,(X),94.5,1.3,5.5,1.3,94.5,1.3
4,"Hoover city, Alabama",92427,N,N,N,N,N,N,N,N,...,(X),(X),92427,(X),95.2,2.3,4.8,2.3,95.2,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,725,586,1078,596,1271,813,99,185,...,(X),(X),143279,(X),81.6,3.8,18.4,3.8,81.6,3.8
196,"Westminster city, Colorado",114539,1198,929,849,689,468,427,454,348,...,(X),(X),114539,(X),85.1,2.7,14.9,2.7,85.1,2.7
197,"Bridgeport city, Connecticut",148365,N,N,N,N,N,N,N,N,...,(X),(X),148365,(X),81.8,3.7,18.2,3.7,81.8,3.7
198,"Danbury city, Connecticut",86971,N,N,N,N,N,N,N,N,...,(X),(X),86971,(X),76.7,5.3,23.3,5.3,76.7,5.3
199,"Hartford city, Connecticut",120682,963,677,1512,970,37,63,0,224,...,(X),(X),120682,(X),86.8,2.9,13.2,2.9,86.8,2.9

In [85]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0045E', 'DP05_0045M', 'DP05_0046E',
       'DP05_0046M', 'DP05_0047E', 'DP05_0047M', 'DP05_0048E', 'DP05_0048M',
       ...
       'DP05_0032PE', 'DP05_0032PM', 'DP05_0033PE', 'DP05_0033PM',
       'DP05_0034PE', 'DP05_0034PM', 'DP05_0035PE', 'DP05_0035PM',
       'DP05_0036PE', 'DP05_0036PM'],
      dtype='object', length=168)

In [86]:
population2_df.drop (columns=['DP05_0045E', 'DP05_0045M', 'DP05_0046E',
       'DP05_0046M', 'DP05_0047E', 'DP05_0047M', 'DP05_0048E', 'DP05_0048M',
       'DP05_0032PE', 'DP05_0032PM', 'DP05_0033PE', 'DP05_0033PM',
       'DP05_0034PE', 'DP05_0034PM', 'DP05_0035PE', 'DP05_0035PM',
       'DP05_0036PE', 'DP05_0036PM']
    
, inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0049E,DP05_0049M,DP05_0050E,DP05_0050M,DP05_0051E,DP05_0051M,DP05_0052E,DP05_0052M,...,DP05_0027PE,DP05_0027PM,DP05_0028PE,DP05_0028PM,DP05_0029PE,DP05_0029PM,DP05_0030PE,DP05_0030PM,DP05_0031PE,DP05_0031PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!As...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Na...,Margin of Error!!RACE!!Total population!!One r...,...,Percent!!SEX AND AGE!!Total population!!18 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!18 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!65 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!65 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!65 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...
1,"Auburn city, Alabama",80009,3048,1223,391,497,997,701,0,208,...,50.6,1.9,(X),(X),6540,(X),45.4,7.2,54.6,7.2
2,"Birmingham city, Alabama",196353,N,N,N,N,N,N,23,43,...,54.3,1.3,(X),(X),30814,(X),40,2.6,60,2.6
3,"Dothan city, Alabama",70524,N,N,N,N,N,N,0,208,...,53.7,1.3,(X),(X),13464,(X),41.3,2.3,58.7,2.3
4,"Hoover city, Alabama",92427,N,N,N,N,N,N,0,208,...,54,2.7,(X),(X),17643,(X),40.8,4.8,59.2,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,715,598,824,673,4103,2621,5,6,...,52.3,1.5,(X),(X),16248,(X),43.2,4,56.8,4
196,"Westminster city, Colorado",114539,995,614,964,853,3307,1598,85,150,...,47.9,1.9,(X),(X),16344,(X),45.7,4,54.3,4
197,"Bridgeport city, Connecticut",148365,N,N,N,N,N,N,0,224,...,50.1,1.8,(X),(X),22554,(X),48.7,3.9,51.3,3.9
198,"Danbury city, Connecticut",86971,N,N,N,N,N,N,96,76,...,49.6,2.3,(X),(X),12861,(X),48.7,5.6,51.3,5.6
199,"Hartford city, Connecticut",120682,0,224,1237,972,530,471,0,224,...,51.5,2.5,(X),(X),14809,(X),38.7,5,61.3,5

In [87]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0049E', 'DP05_0049M', 'DP05_0050E',
       'DP05_0050M', 'DP05_0051E', 'DP05_0051M', 'DP05_0052E', 'DP05_0052M',
       ...
       'DP05_0027PE', 'DP05_0027PM', 'DP05_0028PE', 'DP05_0028PM',
       'DP05_0029PE', 'DP05_0029PM', 'DP05_0030PE', 'DP05_0030PM',
       'DP05_0031PE', 'DP05_0031PM'],
      dtype='object', length=150)

In [88]:
population2_df.drop (columns=['DP05_0049E', 'DP05_0049M', 'DP05_0050E',
       'DP05_0050M', 'DP05_0051E', 'DP05_0051M', 'DP05_0052E', 'DP05_0052M',
       'DP05_0027PE', 'DP05_0027PM', 'DP05_0028PE', 'DP05_0028PM',
       'DP05_0029PE', 'DP05_0029PM', 'DP05_0030PE', 'DP05_0030PM',
       'DP05_0031PE', 'DP05_0031PM']
    
, inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0053E,DP05_0053M,DP05_0054E,DP05_0054M,DP05_0055E,DP05_0055M,DP05_0056E,DP05_0056M,...,DP05_0022PE,DP05_0022PM,DP05_0023PE,DP05_0023PM,DP05_0024PE,DP05_0024PM,DP05_0025PE,DP05_0025PM,DP05_0026PE,DP05_0026PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!One race!!Na...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Na...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Na...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!One race!!Na...,Margin of Error!!RACE!!Total population!!One r...,...,Percent!!SEX AND AGE!!Total population!!21 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!62 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!65 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!18 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!18 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...
1,"Auburn city, Alabama",80009,N,N,N,N,N,N,N,N,...,64.1,3.1,9.8,1.8,8.2,1.7,65224,(X),49.4,1.9
2,"Birmingham city, Alabama",196353,N,N,N,N,N,N,N,N,...,75.3,1.7,20,1.4,15.7,1.1,158268,(X),45.7,1.3
3,"Dothan city, Alabama",70524,N,N,N,N,N,N,N,N,...,73.3,1.5,22.7,1.3,19.1,1,54298,(X),46.3,1.3
4,"Hoover city, Alabama",92427,N,N,N,N,N,N,N,N,...,71.7,3.5,23.4,3.2,19.1,2.7,69745,(X),46,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,N,N,N,N,N,N,N,N,...,71.1,2.5,14.5,1.9,11.3,1.5,107540,(X),47.7,1.5
196,"Westminster city, Colorado",114539,N,N,N,N,N,N,N,N,...,78,2.2,16.6,2,14.3,1.8,93473,(X),52.1,1.9
197,"Bridgeport city, Connecticut",148365,N,N,N,N,N,N,N,N,...,74.8,1.9,19.2,2.1,15.2,1.9,117978,(X),49.9,1.8
198,"Danbury city, Connecticut",86971,N,N,N,N,N,N,N,N,...,70.1,3.7,18,3.6,14.8,3,66992,(X),50.4,2.3
199,"Hartford city, Connecticut",120682,N,N,N,N,N,N,N,N,...,71.5,2.4,14.6,1.8,12.3,1.6,95142,(X),48.5,2.5

In [89]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0053E', 'DP05_0053M', 'DP05_0054E',
       'DP05_0054M', 'DP05_0055E', 'DP05_0055M', 'DP05_0056E', 'DP05_0056M',
       ...
       'DP05_0022PE', 'DP05_0022PM', 'DP05_0023PE', 'DP05_0023PM',
       'DP05_0024PE', 'DP05_0024PM', 'DP05_0025PE', 'DP05_0025PM',
       'DP05_0026PE', 'DP05_0026PM'],
      dtype='object', length=132)

In [90]:
population2_df.drop (columns=['DP05_0053E', 'DP05_0053M', 'DP05_0054E',
       'DP05_0054M', 'DP05_0055E', 'DP05_0055M', 'DP05_0056E', 'DP05_0056M',         
                              
       'DP05_0022PE', 'DP05_0022PM', 'DP05_0023PE', 'DP05_0023PM',
       'DP05_0024PE', 'DP05_0024PM', 'DP05_0025PE', 'DP05_0025PM',
       'DP05_0026PE', 'DP05_0026PM']
    
, inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0057E,DP05_0057M,DP05_0058E,DP05_0058M,DP05_0059E,DP05_0059M,DP05_0060E,DP05_0060M,...,DP05_0017PE,DP05_0017PM,DP05_0018PE,DP05_0018PM,DP05_0019PE,DP05_0019PM,DP05_0020PE,DP05_0020PM,DP05_0021PE,DP05_0021PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!One race!!So...,Margin of Error!!RACE!!Total population!!One r...,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,...,Percent!!SEX AND AGE!!Total population!!85 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!Median...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!Under ...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!16 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!18 yea...,Percent Margin of Error!!SEX AND AGE!!Total po...
1,"Auburn city, Alabama",80009,2521,1685,3949,1782,483,452,347,308,...,0.6,0.4,(X),(X),18.5,2.5,84.6,2.4,81.5,2.5
2,"Birmingham city, Alabama",196353,4549,1904,4408,1206,811,587,462,226,...,1.8,0.4,(X),(X),19.4,1.7,82.6,1.7,80.6,1.7
3,"Dothan city, Alabama",70524,875,504,3886,910,787,471,479,162,...,1.9,0.5,(X),(X),23,1.3,79.3,1.3,77,1.3
4,"Hoover city, Alabama",92427,372,326,4479,2099,N,N,N,N,...,3.5,1.4,(X),(X),24.5,3.3,78.3,3.3,75.5,3.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,16851,5702,26354,5484,804,752,1483,760,...,0.5,0.3,(X),(X),24.9,2.4,78.6,2.5,75.1,2.4
196,"Westminster city, Colorado",114539,5270,2554,17119,3139,1468,742,786,487,...,1.3,0.6,(X),(X),18.4,2.5,83.4,2.4,81.6,2.5
197,"Bridgeport city, Connecticut",148365,29926,6347,26936,5434,205,223,0,224,...,1.3,0.5,(X),(X),20.5,1.8,81.9,1.9,79.5,1.8
198,"Danbury city, Connecticut",86971,18740,5416,20264,4645,1827,1395,211,199,...,1.8,0.6,(X),(X),23,3.4,80.4,3.3,77,3.4
199,"Hartford city, Connecticut",120682,27051,5119,15876,3498,7241,2607,330,229,...,1.3,0.5,(X),(X),21.2,2.2,80.1,2.3,78.8,2.2

In [91]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0057E', 'DP05_0057M', 'DP05_0058E',
       'DP05_0058M', 'DP05_0059E', 'DP05_0059M', 'DP05_0060E', 'DP05_0060M',
       ...
       'DP05_0017PE', 'DP05_0017PM', 'DP05_0018PE', 'DP05_0018PM',
       'DP05_0019PE', 'DP05_0019PM', 'DP05_0020PE', 'DP05_0020PM',
       'DP05_0021PE', 'DP05_0021PM'],
      dtype='object', length=114)

In [92]:
population2_df.drop (columns=['DP05_0057E', 'DP05_0057M', 'DP05_0058E',
       'DP05_0058M', 'DP05_0059E', 'DP05_0059M', 'DP05_0060E', 'DP05_0060M',
       'DP05_0017PE', 'DP05_0017PM', 'DP05_0018PE', 'DP05_0018PM',
       'DP05_0019PE', 'DP05_0019PM', 'DP05_0020PE', 'DP05_0020PM',
       'DP05_0021PE', 'DP05_0021PM']
    
, inplace=True)

population2_df.head (200)

,NAME,DP05_0001E,DP05_0061E,DP05_0061M,DP05_0062E,DP05_0062M,DP05_0063E,DP05_0063M,DP05_0064E,DP05_0064M,...,DP05_0012PE,DP05_0012PM,DP05_0013PE,DP05_0013PM,DP05_0014PE,DP05_0014PM,DP05_0015PE,DP05_0015PM,DP05_0016PE,DP05_0016PM
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,Estimate!!RACE!!Total population!!Two or More ...,Margin of Error!!RACE!!Total population!!Two o...,...,Percent!!SEX AND AGE!!Total population!!45 to ...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!55 to ...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!60 to ...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!65 to ...,Percent Margin of Error!!SEX AND AGE!!Total po...,Percent!!SEX AND AGE!!Total population!!75 to ...,Percent Margin of Error!!SEX AND AGE!!Total po...
1,"Auburn city, Alabama",80009,633,617,1033,783,0,208,0,208,...,10.3,1.8,3.7,1.2,3.8,1.1,4.8,1.3,2.8,0.9
2,"Birmingham city, Alabama",196353,69,111,2229,1038,45,76,180,216,...,10.8,1.2,6,1,6.6,0.9,10.1,1,3.8,0.6
3,"Dothan city, Alabama",70524,176,102,1659,667,303,314,104,121,...,11.3,1,6.1,0.8,6.3,0.9,11.6,0.8,5.7,0.8
4,"Hoover city, Alabama",92427,N,N,N,N,N,N,N,N,...,13.2,2.1,4.4,1.1,7.9,1.7,9.9,2,5.7,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,"Thornton city, Colorado",143279,2289,1036,20279,5311,0,218,32,55,...,13,1.7,4.9,1.2,4.7,1.2,8,1.3,2.9,0.8
196,"Westminster city, Colorado",114539,1356,681,12025,3256,0,218,134,217,...,13.2,1.9,5.2,1.1,4.4,1.1,8.9,1.2,4,0.9
197,"Bridgeport city, Connecticut",148365,666,702,16826,4645,1006,921,6026,3285,...,10.9,1.3,6.9,1.5,7.5,1.2,8.7,1,5.3,1.2
198,"Danbury city, Connecticut",86971,105,166,13739,4028,385,471,2537,1548,...,12.4,2.5,7.2,1.9,4.9,1.8,9.3,2.2,3.7,1.1
199,"Hartford city, Connecticut",120682,446,315,4231,1761,1333,1252,404,371,...,12,1.9,6.8,1.2,3.6,1,7.3,1.2,3.6,0.8

In [93]:
population2_df.columns

Index(['NAME', 'DP05_0001E', 'DP05_0061E', 'DP05_0061M', 'DP05_0062E',
       'DP05_0062M', 'DP05_0063E', 'DP05_0063M', 'DP05_0064E', 'DP05_0064M',
       'DP05_0065E', 'DP05_0065M', 'DP05_0066E', 'DP05_0066M', 'DP05_0067E',
       'DP05_0067M', 'DP05_0068E', 'DP05_0068M', 'DP05_0069E', 'DP05_0069M',
       'DP05_0070E', 'DP05_0070M', 'DP05_0071E', 'DP05_0071M', 'DP05_0072E',
       'DP05_0072M', 'DP05_0073E', 'DP05_0073M', 'DP05_0074E', 'DP05_0074M',
       'DP05_0075E', 'DP05_0075M', 'DP05_0076E', 'DP05_0076M', 'DP05_0077E',
       'DP05_0077M', 'DP05_0078E', 'DP05_0078M', 'DP05_0079E', 'DP05_0079M',
       'DP05_0080E', 'DP05_0080M', 'DP05_0081E', 'DP05_0081M', 'DP05_0082E',
       'DP05_0082M', 'DP05_0083E', 'DP05_0083M', 'DP05_0084E', 'DP05_0084M',
       'DP05_0085E', 'DP05_0085M', 'DP05_0086E', 'DP05_0086M', 'DP05_0087E',
       'DP05_0087M', 'DP05_0088E', 'DP05_0088M', 'DP05_0089E', 'DP05_0089M',
       'DP05_0090E', 'DP05_0090M', 'DP05_0091E', 'DP05_0091M', 'DP05_0001PE',
       'DP05_0001PM', 'DP05_0002PE', 'DP05_0002PM', 'DP05_0003PE',
       'DP05_0003PM', 'DP05_0004PE', 'DP05_0004PM', 'DP05_0005PE',
       'DP05_0005PM', 'DP05_0006PE', 'DP05_0006PM', 'DP05_0007PE',
       'DP05_0007PM', 'DP05_0008PE', 'DP05_0008PM', 'DP05_0009PE',
       'DP05_0009PM', 'DP05_0010PE', 'DP05_0010PM', 'DP05_0011PE',
       'DP05_0011PM', 'DP05_0012PE', 'DP05_0012PM', 'DP05_0013PE',
       'DP05_0013PM', 'DP05_0014PE', 'DP05_0014PM', 'DP05_0015PE',
       'DP05_0015PM', 'DP05_0016PE', 'DP05_0016PM'],
      dtype='object')

In [94]:
population2_df.drop (columns=['DP05_0061E', 'DP05_0061M', 'DP05_0062E',
       'DP05_0062M', 'DP05_0063E', 'DP05_0063M', 'DP05_0064E', 'DP05_0064M',
       'DP05_0065E', 'DP05_0065M', 'DP05_0066E', 'DP05_0066M', 'DP05_0067E',
       'DP05_0067M', 'DP05_0068E', 'DP05_0068M', 'DP05_0069E', 'DP05_0069M',
       'DP05_0070E', 'DP05_0070M', 'DP05_0071E', 'DP05_0071M', 'DP05_0072E',
       'DP05_0072M', 'DP05_0073E', 'DP05_0073M', 'DP05_0074E', 'DP05_0074M',
       'DP05_0075E', 'DP05_0075M', 'DP05_0076E', 'DP05_0076M', 'DP05_0077E',
       'DP05_0077M', 'DP05_0078E', 'DP05_0078M', 'DP05_0079E', 'DP05_0079M',
       'DP05_0080E', 'DP05_0080M', 'DP05_0081E', 'DP05_0081M', 'DP05_0082E',
       'DP05_0082M', 'DP05_0083E', 'DP05_0083M', 'DP05_0084E', 'DP05_0084M',
       'DP05_0085E', 'DP05_0085M', 'DP05_0086E', 'DP05_0086M', 'DP05_0087E',
       'DP05_0087M', 'DP05_0088E', 'DP05_0088M', 'DP05_0089E', 'DP05_0089M',
       'DP05_0090E', 'DP05_0090M', 'DP05_0091E', 'DP05_0091M', 'DP05_0001PE',
       'DP05_0001PM', 'DP05_0002PE', 'DP05_0002PM', 'DP05_0003PE',
       'DP05_0003PM', 'DP05_0004PE', 'DP05_0004PM', 'DP05_0005PE',
       'DP05_0005PM', 'DP05_0006PE', 'DP05_0006PM', 'DP05_0007PE',
       'DP05_0007PM', 'DP05_0008PE', 'DP05_0008PM', 'DP05_0009PE',
       'DP05_0009PM', 'DP05_0010PE', 'DP05_0010PM', 'DP05_0011PE',
       'DP05_0011PM', 'DP05_0012PE', 'DP05_0012PM', 'DP05_0013PE',
       'DP05_0013PM', 'DP05_0014PE', 'DP05_0014PM', 'DP05_0015PE',
       'DP05_0015PM', 'DP05_0016PE', 'DP05_0016PM']
    
, inplace=True)

population2_df.head (200)

                             NAME                               DP05_0001E
0            Geographic Area Name  Estimate!!SEX AND AGE!!Total population
1            Auburn city, Alabama                                    80009
2        Birmingham city, Alabama                                   196353
3            Dothan city, Alabama                                    70524
4            Hoover city, Alabama                                    92427
..                            ...                                      ...
195       Thornton city, Colorado                                   143279
196    Westminster city, Colorado                                   114539
197  Bridgeport city, Connecticut                                   148365
198     Danbury city, Connecticut                                    86971
199    Hartford city, Connecticut                                   120682

[200 rows x 2 columns]

In [95]:
rows_to_delete = [0]
population2_df.drop(rows_to_delete, inplace=True)

population2_df.head (200)

                              NAME DP05_0001E
1             Auburn city, Alabama      80009
2         Birmingham city, Alabama     196353
3             Dothan city, Alabama      70524
4             Hoover city, Alabama      92427
5         Huntsville city, Alabama     222363
..                             ...        ...
196     Westminster city, Colorado     114539
197   Bridgeport city, Connecticut     148365
198      Danbury city, Connecticut      86971
199     Hartford city, Connecticut     120682
200  New Britain city, Connecticut      74408

[200 rows x 2 columns]

In [96]:
new_column_names = ['City2', 'Total Population']


population2_df.columns = new_column_names

In [97]:
population2_df.head (200)

                             City2 Total Population
1             Auburn city, Alabama            80009
2         Birmingham city, Alabama           196353
3             Dothan city, Alabama            70524
4             Hoover city, Alabama            92427
5         Huntsville city, Alabama           222363
..                             ...              ...
196     Westminster city, Colorado           114539
197   Bridgeport city, Connecticut           148365
198      Danbury city, Connecticut            86971
199     Hartford city, Connecticut           120682
200  New Britain city, Connecticut            74408

[200 rows x 2 columns]

In [98]:
population2_df[['City', 'State']] = population2_df['City2'].str.split(', ', n=1, expand=True)

population2_df = population2_df.drop('City2', axis=1)

In [99]:
population2_df.head (200)

    Total Population              City        State
1              80009       Auburn city      Alabama
2             196353   Birmingham city      Alabama
3              70524       Dothan city      Alabama
4              92427       Hoover city      Alabama
5             222363   Huntsville city      Alabama
..               ...               ...          ...
196           114539  Westminster city     Colorado
197           148365   Bridgeport city  Connecticut
198            86971      Danbury city  Connecticut
199           120682     Hartford city  Connecticut
200            74408  New Britain city  Connecticut

[200 rows x 3 columns]

In [100]:
population2_df['City'] = population2_df['City'].str.replace(' city', '', case=False)


population2_df.head(200)

    Total Population         City        State
1              80009       Auburn      Alabama
2             196353   Birmingham      Alabama
3              70524       Dothan      Alabama
4              92427       Hoover      Alabama
5             222363   Huntsville      Alabama
..               ...          ...          ...
196           114539  Westminster     Colorado
197           148365   Bridgeport  Connecticut
198            86971      Danbury  Connecticut
199           120682     Hartford  Connecticut
200            74408  New Britain  Connecticut

[200 rows x 3 columns]

In [101]:
population2_df = population2_df[['City', 'State', 'Total Population']]


population2_df.head(200)

            City        State Total Population
1         Auburn      Alabama            80009
2     Birmingham      Alabama           196353
3         Dothan      Alabama            70524
4         Hoover      Alabama            92427
5     Huntsville      Alabama           222363
..           ...          ...              ...
196  Westminster     Colorado           114539
197   Bridgeport  Connecticut           148365
198      Danbury  Connecticut            86971
199     Hartford  Connecticut           120682
200  New Britain  Connecticut            74408

[200 rows x 3 columns]

In [103]:
csv_file_path = 'Census_Population_By_City.csv'


population2_df.to_csv(csv_file_path, index=False)