In [55]:
import pandas as pd
from pathlib import Path

In [56]:
population=Path ('population_total.csv')

In [87]:
population_df= pd.read_csv(population)
population_df.head (200)

,Label (Grouping),Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,Arizona!!Estimate,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
0,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total population,"5,074,296",*****,"5,074,296",(X),"733,583",*****,"733,583",(X),"7,359,197",...,"5,892,539",(X),"581,381",*****,"581,381",(X),"3,221,789",*****,"3,221,789",(X)
2,Male,"2,461,248","±6,178",48.5%,±0.1,"385,667","±2,351",52.6%,±0.3,"3,678,381",...,50.2%,±0.1,"297,855","±2,038",51.2%,±0.4,"1,528,789","±3,493",47.5%,±0.1
3,Female,"2,613,048","±6,178",51.5%,±0.1,"347,916","±2,351",47.4%,±0.3,"3,680,816",...,49.8%,±0.1,"283,526","±2,038",48.8%,±0.4,"1,693,000","±3,493",52.5%,±0.1
4,Sex ratio (males per 100 females),94.2,±0.5,(X),(X),110.9,±1.4,(X),(X),99.9,...,(X),(X),105.1,±1.5,(X),(X),90.3,±0.4,(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Total housing units,"2,339,582",±307,(X),(X),"329,160",±406,(X),(X),"3,186,554",...,(X),(X),"277,106",±67,(X),(X),"1,598,570","±7,274",(X),(X)
92,"CITIZEN, VOTING AGE POPULATION",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,"Citizen, 18 and over population","3,862,490","±7,890","3,862,490",(X),"537,962","±3,066","537,962",(X),"5,322,581",...,"4,511,381",(X),"442,829","±2,165","442,829",(X),"2,666,630","±3,981","2,666,630",(X)
94,Male,"1,838,188","±5,264",47.6%,±0.1,"286,333","±2,449",53.2%,±0.3,"2,640,533",...,49.7%,±0.1,"225,657","±2,162",51.0%,±0.4,"1,242,825","±2,349",46.6%,±0.1
95,Female,"2,024,302","±4,729",52.4%,±0.1,"251,629","±2,046",46.8%,±0.3,"2,682,048",...,50.3%,±0.1,"217,172","±1,615",49.0%,±0.4,"1,423,805","±2,767",53.4%,±0.1

In [88]:
population_df.describe()

,Label (Grouping),Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,Arizona!!Estimate,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
count,96,91,91,91,91,91,91,91,91,91,...,91,91,91,91,91,91,91,91,91,91
unique,84,81,76,57,5,84,79,64,10,84,...,56,4,81,76,58,11,69,56,50,9
top,Total population,"5,074,296",*****,0.3%,±0.1,"733,583",*****,(X),±0.3,"7,359,197",...,0.1%,±0.1,"581,381",*****,0.1%,±0.1,N,*****,N,±0.1
freq,4,4,4,6,60,4,6,5,17,4,...,6,66,4,6,8,19,15,16,15,33

In [89]:
population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Columns: 209 entries, Label (Grouping) to Puerto Rico!!Percent Margin of Error
dtypes: object(209)
memory usage: 156.9+ KB

In [90]:
population_df=population_df.set_index("Label (Grouping)")

In [91]:
population_df.head (200)

,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,Arizona!!Estimate,Arizona!!Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
Label (Grouping),,,,,,,,,,,,,,,,,,,,,
SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total population,"5,074,296",*****,"5,074,296",(X),"733,583",*****,"733,583",(X),"7,359,197",*****,...,"5,892,539",(X),"581,381",*****,"581,381",(X),"3,221,789",*****,"3,221,789",(X)
Male,"2,461,248","±6,178",48.5%,±0.1,"385,667","±2,351",52.6%,±0.3,"3,678,381","±2,695",...,50.2%,±0.1,"297,855","±2,038",51.2%,±0.4,"1,528,789","±3,493",47.5%,±0.1
Female,"2,613,048","±6,178",51.5%,±0.1,"347,916","±2,351",47.4%,±0.3,"3,680,816","±2,695",...,49.8%,±0.1,"283,526","±2,038",48.8%,±0.4,"1,693,000","±3,493",52.5%,±0.1
Sex ratio (males per 100 females),94.2,±0.5,(X),(X),110.9,±1.4,(X),(X),99.9,±0.1,...,(X),(X),105.1,±1.5,(X),(X),90.3,±0.4,(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Total housing units,"2,339,582",±307,(X),(X),"329,160",±406,(X),(X),"3,186,554",±496,...,(X),(X),"277,106",±67,(X),(X),"1,598,570","±7,274",(X),(X)
"CITIZEN, VOTING AGE POPULATION",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Citizen, 18 and over population","3,862,490","±7,890","3,862,490",(X),"537,962","±3,066","537,962",(X),"5,322,581","±14,737",...,"4,511,381",(X),"442,829","±2,165","442,829",(X),"2,666,630","±3,981","2,666,630",(X)
Male,"1,838,188","±5,264",47.6%,±0.1,"286,333","±2,449",53.2%,±0.3,"2,640,533","±9,815",...,49.7%,±0.1,"225,657","±2,162",51.0%,±0.4,"1,242,825","±2,349",46.6%,±0.1
Female,"2,024,302","±4,729",52.4%,±0.1,"251,629","±2,046",46.8%,±0.3,"2,682,048","±8,862",...,50.3%,±0.1,"217,172","±1,615",49.0%,±0.4,"1,423,805","±2,767",53.4%,±0.1

In [92]:
final_population_df=population_df.T
final_population_df.head (200)

Label (Grouping),SEX AND AGE,Total population,Male,Female,Sex ratio (males per 100 females),Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,...,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Two or More Races,Two races including Some Other Race,"Two races excluding Some Other Race, and three or more races",Total housing units,"CITIZEN, VOTING AGE POPULATION","Citizen, 18 and over population",Male,Female
Alabama!!Estimate,NaN,"5,074,296","2,461,248","2,613,048",94.2,"284,064","311,592","318,523","340,067","345,126",...,"1,954","19,927","169,880","23,323","146,557","2,339,582",NaN,"3,862,490","1,838,188","2,024,302"
Alabama!!Margin of Error,NaN,*****,"±6,178","±6,178",±0.5,"±3,192","±7,473","±6,736","±5,792","±5,567",...,±946,"±4,843","±9,324","±3,018","±9,076",±307,NaN,"±7,890","±5,264","±4,729"
Alabama!!Percent,NaN,"5,074,296",48.5%,51.5%,(X),5.6%,6.1%,6.3%,6.7%,6.8%,...,0.0%,0.4%,3.3%,0.5%,2.9%,(X),NaN,"3,862,490",47.6%,52.4%
Alabama!!Percent Margin of Error,NaN,(X),±0.1,±0.1,(X),±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,±0.2,±0.1,±0.2,(X),NaN,(X),±0.1,±0.1
Alaska!!Estimate,NaN,"733,583","385,667","347,916",110.9,"46,497","49,637","51,178","44,794","52,259",...,"14,539","4,034","78,552","7,898","70,654","329,160",NaN,"537,962","286,333","251,629"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Virginia!!Percent Margin of Error,NaN,(X),±0.2,±0.2,(X),±0.1,±0.2,±0.3,±0.2,±0.2,...,±0.1,±0.1,±0.3,±0.2,±0.2,(X),NaN,(X),±0.1,±0.1
Wisconsin!!Estimate,NaN,"5,892,539","2,958,771","2,933,768",100.9,"309,244","333,686","369,101","385,002","407,006",...,"2,592","19,680","217,532","51,594","165,938","2,770,355",NaN,"4,511,381","2,243,395","2,267,986"
Wisconsin!!Margin of Error,NaN,*****,"±4,037","±4,037",±0.3,"±2,162","±6,625","±6,227","±3,621","±3,603",...,"±1,856","±3,383","±9,154","±5,320","±8,054",±641,NaN,"±7,993","±4,982","±5,761"
Wisconsin!!Percent,NaN,"5,892,539",50.2%,49.8%,(X),5.2%,5.7%,6.3%,6.5%,6.9%,...,0.0%,0.3%,3.7%,0.9%,2.8%,(X),NaN,"4,511,381",49.7%,50.3%
Wisconsin!!Percent Margin of Error,NaN,(X),±0.1,±0.1,(X),±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,±0.2,±0.1,±0.1,(X),NaN,(X),±0.1,±0.1

In [93]:
final_population_df.columns

Index(['SEX AND AGE', '    Total population', '        Male', '        Female',
       '        Sex ratio (males per 100 females)', '        Under 5 years',
       '        5 to 9 years', '        10 to 14 years',
       '        15 to 19 years', '        20 to 24 years',
       '        25 to 34 years', '        35 to 44 years',
       '        45 to 54 years', '        55 to 59 years',
       '        60 to 64 years', '        65 to 74 years',
       '        75 to 84 years', '        85 years and over',
       '        Median age (years)', '        Under 18 years',
       '        16 years and over', '        18 years and over',
       '        21 years and over', '        62 years and over',
       '        65 years and over', '        18 years and over',
       '            Male', '            Female',
       '            Sex ratio (males per 100 females)',
       '        65 years and over', '            Male', '            Female',
       '            Sex ratio (males per 100 females)', 'RACE',
       '    Total population', '        One race', '        Two or More Races',
       '        One race', '            White',
       '            Black or African American',
       '            American Indian and Alaska Native',
       '                Cherokee tribal grouping',
       '                Chippewa tribal grouping',
       '                Navajo tribal grouping',
       '                Sioux tribal grouping', '            Asian',
       '                Asian Indian', '                Chinese',
       '                Filipino', '                Japanese',
       '                Korean', '                Vietnamese',
       '                Other Asian',
       '            Native Hawaiian and Other Pacific Islander',
       '                Chamorro', '                Native Hawaiian',
       '                Samoan',
       '                Other Native Hawaiian and Other Pacific Islander',
       '            Some Other Race', '        Two or More Races',
       '            White and Black or African American',
       '            White and American Indian and Alaska Native',
       '            White and Asian', '            White and Some Other Race',
       '            Black or African American and American Indian and Alaska Native',
       '            Black or African American and Some Other Race',
       'Race alone or in combination with one or more other races',
       '    Total population', '        White',
       '        Black or African American',
       '        American Indian and Alaska Native', '        Asian',
       '        Native Hawaiian and Other Pacific Islander',
       '        Some Other Race', 'HISPANIC OR LATINO AND RACE',
       '    Total population', '        Hispanic or Latino (of any race)',
       '            Mexican', '            Puerto Rican', '            Cuban',
       '            Other Hispanic or Latino',
       '        Not Hispanic or Latino', '            White alone',
       '            Black or African American alone',
       '            American Indian and Alaska Native alone',
       '            Asian alone',
       '            Native Hawaiian and Other Pacific Islander alone',
       '            Some Other Race alone', '            Two or More Races',
       '                Two races including Some Other Race',
       '                Two races excluding Some Other Race, and three or more races',
       'Total housing units', 'CITIZEN, VOTING AGE POPULATION',
       '    Citizen, 18 and over population', '        Male',
       '        Female'],
      dtype='object', name='Label (Grouping)')

In [94]:
final_population_df=final_population_df.reset_index()
final_population_df.head (200)

Label (Grouping),index,SEX AND AGE,Total population,Male,Female,Sex ratio (males per 100 females),Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,...,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Two or More Races,Two races including Some Other Race,"Two races excluding Some Other Race, and three or more races",Total housing units,"CITIZEN, VOTING AGE POPULATION","Citizen, 18 and over population",Male,Female
0,Alabama!!Estimate,NaN,"5,074,296","2,461,248","2,613,048",94.2,"284,064","311,592","318,523","340,067",...,"1,954","19,927","169,880","23,323","146,557","2,339,582",NaN,"3,862,490","1,838,188","2,024,302"
1,Alabama!!Margin of Error,NaN,*****,"±6,178","±6,178",±0.5,"±3,192","±7,473","±6,736","±5,792",...,±946,"±4,843","±9,324","±3,018","±9,076",±307,NaN,"±7,890","±5,264","±4,729"
2,Alabama!!Percent,NaN,"5,074,296",48.5%,51.5%,(X),5.6%,6.1%,6.3%,6.7%,...,0.0%,0.4%,3.3%,0.5%,2.9%,(X),NaN,"3,862,490",47.6%,52.4%
3,Alabama!!Percent Margin of Error,NaN,(X),±0.1,±0.1,(X),±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,±0.2,±0.1,±0.2,(X),NaN,(X),±0.1,±0.1
4,Alaska!!Estimate,NaN,"733,583","385,667","347,916",110.9,"46,497","49,637","51,178","44,794",...,"14,539","4,034","78,552","7,898","70,654","329,160",NaN,"537,962","286,333","251,629"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,West Virginia!!Percent Margin of Error,NaN,(X),±0.2,±0.2,(X),±0.1,±0.2,±0.3,±0.2,...,±0.1,±0.1,±0.3,±0.2,±0.2,(X),NaN,(X),±0.1,±0.1
196,Wisconsin!!Estimate,NaN,"5,892,539","2,958,771","2,933,768",100.9,"309,244","333,686","369,101","385,002",...,"2,592","19,680","217,532","51,594","165,938","2,770,355",NaN,"4,511,381","2,243,395","2,267,986"
197,Wisconsin!!Margin of Error,NaN,*****,"±4,037","±4,037",±0.3,"±2,162","±6,625","±6,227","±3,621",...,"±1,856","±3,383","±9,154","±5,320","±8,054",±641,NaN,"±7,993","±4,982","±5,761"
198,Wisconsin!!Percent,NaN,"5,892,539",50.2%,49.8%,(X),5.2%,5.7%,6.3%,6.5%,...,0.0%,0.3%,3.7%,0.9%,2.8%,(X),NaN,"4,511,381",49.7%,50.3%
199,Wisconsin!!Percent Margin of Error,NaN,(X),±0.1,±0.1,(X),±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,±0.2,±0.1,±0.1,(X),NaN,(X),±0.1,±0.1

In [95]:
final_population_df.drop (columns=['SEX AND AGE', '        Male',
       '        Female', '        Sex ratio (males per 100 females)',
       '        Under 5 years', '        5 to 9 years',
       '        10 to 14 years', '        15 to 19 years',
       '        Under 18 years', '        16 years and over', '            Male', '            Female',
       '            Sex ratio (males per 100 females)',
       '        65 years and over', '            Male', '            Female',
       '            Sex ratio (males per 100 females)', 'RACE', '        One race', '        Two or More Races',
       '        One race', '            White',
       '            Black or African American',
       '            American Indian and Alaska Native',
       '                Cherokee tribal grouping',
       '                Chippewa tribal grouping',
       '                Navajo tribal grouping',
       '                Sioux tribal grouping', '            Asian',
       '                Asian Indian', '                Chinese',
       '                Filipino', '                Japanese',
       '                Korean', '                Vietnamese',
       '                Other Asian',
       '            Native Hawaiian and Other Pacific Islander',
       '                Chamorro', '                Native Hawaiian',
       '                Samoan',
       '                Other Native Hawaiian and Other Pacific Islander',
       '            Some Other Race', '        Two or More Races',
       '            White and Black or African American',
       '            White and American Indian and Alaska Native',
       '            White and Asian', '            White and Some Other Race',
       '            Black or African American and American Indian and Alaska Native',
       '            Black or African American and Some Other Race',
       'Race alone or in combination with one or more other races', '        White',
       '        Black or African American',
       '        American Indian and Alaska Native', '        Asian',
       '        Native Hawaiian and Other Pacific Islander',
       '        Some Other Race', 'HISPANIC OR LATINO AND RACE', '        Hispanic or Latino (of any race)',
       '            Mexican', '            Puerto Rican', '            Cuban',
       '            Other Hispanic or Latino',
       '        Not Hispanic or Latino', '            White alone',
       '            Black or African American alone',
       '            American Indian and Alaska Native alone',
       '            Asian alone',
       '            Native Hawaiian and Other Pacific Islander alone',
       '            Some Other Race alone', '            Two or More Races',
       '                Two races including Some Other Race',
       '                Two races excluding Some Other Race, and three or more races',
       'Total housing units', 'CITIZEN, VOTING AGE POPULATION',
       '    Citizen, 18 and over population', '        Male',
       '        Female'
    
], inplace=True)

In [96]:
final_population_df.head (200)

Label (Grouping),index,Total population,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age (years),18 years and over,21 years and over,62 years and over,18 years and over,Total population,Total population,Total population
0,Alabama!!Estimate,"5,074,296","345,126","652,152","632,416","617,680","318,087","341,576","546,189","281,791","85,033",39.6,"3,963,268","3,740,839","1,115,768","3,963,268","5,074,296","5,074,296","5,074,296"
1,Alabama!!Margin of Error,*****,"±5,567","±6,978","±6,828","±6,741","±8,050","±7,691","±3,401","±4,988","±4,043",±0.2,"±2,849","±7,068","±6,553","±2,849",*****,*****,*****
2,Alabama!!Percent,"5,074,296",6.8%,12.9%,12.5%,12.2%,6.3%,6.7%,10.8%,5.6%,1.7%,(X),78.1%,73.7%,22.0%,"3,963,268","5,074,296","5,074,296","5,074,296"
3,Alabama!!Percent Margin of Error,(X),±0.1,±0.1,±0.1,±0.1,±0.2,±0.2,±0.1,±0.1,±0.1,(X),±0.1,±0.1,±0.1,(X),(X),(X),(X)
4,Alaska!!Estimate,"733,583","52,259","113,900","104,911","81,813","43,503","43,617","68,896","26,870","5,708",35.9,"557,838","530,734","127,751","557,838","733,583","733,583","733,583"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,West Virginia!!Percent Margin of Error,(X),±0.2,±0.2,±0.2,±0.1,±0.2,±0.3,±0.1,±0.2,±0.1,(X),±0.1,±0.2,±0.2,(X),(X),(X),(X)
196,Wisconsin!!Estimate,"5,892,539","407,006","733,729","742,993","692,508","392,381","424,503","658,466","324,703","119,217",40.4,"4,650,759","4,410,387","1,355,209","4,650,759","5,892,539","5,892,539","5,892,539"
197,Wisconsin!!Margin of Error,*****,"±3,603","±4,382","±4,214","±3,795","±6,590","±6,714","±2,205","±5,195","±4,839",±0.2,"±2,042","±6,413","±6,134","±2,042",*****,*****,*****
198,Wisconsin!!Percent,"5,892,539",6.9%,12.5%,12.6%,11.8%,6.7%,7.2%,11.2%,5.5%,2.0%,(X),78.9%,74.8%,23.0%,"4,650,759","5,892,539","5,892,539","5,892,539"
199,Wisconsin!!Percent Margin of Error,(X),±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,(X),±0.1,±0.1,±0.1,(X),(X),(X),(X)

In [97]:
final_population_df = final_population_df.loc[:, ~final_population_df.columns.duplicated()]
final_population_df.head (200)

Label (Grouping),index,Total population,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age (years),18 years and over,21 years and over,62 years and over
0,Alabama!!Estimate,"5,074,296","345,126","652,152","632,416","617,680","318,087","341,576","546,189","281,791","85,033",39.6,"3,963,268","3,740,839","1,115,768"
1,Alabama!!Margin of Error,*****,"±5,567","±6,978","±6,828","±6,741","±8,050","±7,691","±3,401","±4,988","±4,043",±0.2,"±2,849","±7,068","±6,553"
2,Alabama!!Percent,"5,074,296",6.8%,12.9%,12.5%,12.2%,6.3%,6.7%,10.8%,5.6%,1.7%,(X),78.1%,73.7%,22.0%
3,Alabama!!Percent Margin of Error,(X),±0.1,±0.1,±0.1,±0.1,±0.2,±0.2,±0.1,±0.1,±0.1,(X),±0.1,±0.1,±0.1
4,Alaska!!Estimate,"733,583","52,259","113,900","104,911","81,813","43,503","43,617","68,896","26,870","5,708",35.9,"557,838","530,734","127,751"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,West Virginia!!Percent Margin of Error,(X),±0.2,±0.2,±0.2,±0.1,±0.2,±0.3,±0.1,±0.2,±0.1,(X),±0.1,±0.2,±0.2
196,Wisconsin!!Estimate,"5,892,539","407,006","733,729","742,993","692,508","392,381","424,503","658,466","324,703","119,217",40.4,"4,650,759","4,410,387","1,355,209"
197,Wisconsin!!Margin of Error,*****,"±3,603","±4,382","±4,214","±3,795","±6,590","±6,714","±2,205","±5,195","±4,839",±0.2,"±2,042","±6,413","±6,134"
198,Wisconsin!!Percent,"5,892,539",6.9%,12.5%,12.6%,11.8%,6.7%,7.2%,11.2%,5.5%,2.0%,(X),78.9%,74.8%,23.0%
199,Wisconsin!!Percent Margin of Error,(X),±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,(X),±0.1,±0.1,±0.1

In [98]:
rows_to_delete = [1,2,3,5,6,7,9,10,11,13,14,15, 17,18,19, 21, 22, 23, 25,26,27,29,30,31,33,34,35,37,38,39,41,42,43,45,46,47,49,50,51,53,54,55,57,58,59,61,62,63,65,66,67,69,70,71,73,74,75,77,78,79,81,82,83,85,86,87, 89,90,91,93,94,95,97,98,99,101,102,103,105,106,107,109,110,111,113,114,115,117,118,119,121,122,123,125, 126,127,129,130,131,133,134,135,137,138,139,141,142,143,145,146,147,149,150,151,153,154,155, 157,158,159,161,162,163,165,166,167,169,170,171, 173,174,175,177,178,179,181,182,183,185,186,187,189,190,191,193,194,195,197,198,199,201,202,203,205,206,207]
final_population_df.drop(rows_to_delete, inplace=True)

final_population_df.head (200)

Label (Grouping),index,Total population,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age (years),18 years and over,21 years and over,62 years and over
0,Alabama!!Estimate,"5,074,296","345,126","652,152","632,416","617,680","318,087","341,576","546,189","281,791","85,033",39.6,"3,963,268","3,740,839","1,115,768"
4,Alaska!!Estimate,"733,583","52,259","113,900","104,911","81,813","43,503","43,617","68,896","26,870","5,708",35.9,"557,838","530,734","127,751"
8,Arizona!!Estimate,"7,359,197","522,484","1,018,691","926,470","855,266","414,587","456,688","781,078","471,625","129,251",38.8,"5,771,594","5,479,621","1,654,674"
12,Arkansas!!Estimate,"3,045,637","209,906","385,877","387,640","363,403","181,881","199,981","315,159","169,508","54,175",38.9,"2,349,805","2,224,439","658,015"
16,California!!Estimate,"39,029,342","2,639,787","5,744,459","5,395,388","4,877,813","2,356,663","2,333,548","3,568,539","1,878,688","711,675",37.9,"30,530,336","28,971,158","7,528,702"
20,Colorado!!Estimate,"5,839,926","395,695","915,942","860,355","704,694","327,914","359,438","562,352","268,623","84,686",37.7,"4,628,831","4,402,108","1,129,744"
24,Connecticut!!Estimate,"3,626,205","243,507","450,510","460,313","455,401","256,256","258,996","381,828","199,913","81,971",40.9,"2,895,781","2,739,659","818,271"
28,Delaware!!Estimate,"1,018,396","59,981","130,563","125,307","112,870","65,121","78,000","126,996","66,312","18,872",41.5,"810,169","769,624","260,120"
32,District of Columbia!!Estimate,"671,803","48,043","145,253","111,221","71,561","30,859","32,983","50,100","27,846","9,408",34.9,"547,559","519,804","106,696"
36,Florida!!Estimate,"22,244,823","1,340,486","2,783,761","2,799,499","2,734,163","1,472,092","1,520,481","2,604,014","1,638,608","551,792",42.7,"17,949,929","17,173,813","5,701,562"
40,Georgia!!Estimate,"10,912,876","771,563","1,483,997","1,469,050","1,399,249","681,208","655,201","998,558","502,309","143,408",37.6,"8,407,208","7,944,999","2,032,087"
44,Hawaii!!Estimate,"1,440,196","89,347","190,091","192,131","170,144","85,230","91,593","163,041","94,511","37,102",40.8,"1,143,330","1,096,073","349,372"
48,Idaho!!Estimate,"1,939,033","141,188","250,343","256,103","219,658","108,296","116,248","200,204","98,886","30,440",37.5,"1,474,413","1,393,829","399,602"
52,Illinois!!Estimate,"12,582,032","850,982","1,689,818","1,673,268","1,557,011","798,387","809,415","1,262,869","656,343","245,728",39.1,"9,865,826","9,382,977","2,642,662"
56,Indiana!!Estimate,"6,833,037","489,814","886,951","866,145","815,195","414,046","444,697","688,473","350,997","117,956",38.2,"5,263,663","4,970,757","1,424,537"
60,Iowa!!Estimate,"3,200,517","231,721","401,666","405,073","361,104","188,738","214,051","341,121","179,782","67,976",38.9,"2,483,769","2,343,680","716,881"
64,Kansas!!Estimate,"2,937,150","218,626","377,319","382,629","323,536","171,124","183,941","296,501","151,007","58,834",37.6,"2,248,938","2,119,340","613,340"
68,Kentucky!!Estimate,"4,512,310","301,356","587,159","569,323","557,593","279,552","306,759","477,806","235,960","77,347",39.4,"3,507,430","3,332,221","975,245"
72,Louisiana!!Estimate,"4,590,241","315,728","592,066","611,300","533,153","262,705","316,836","472,005","236,926","71,130",38.2,"3,531,381","3,342,828","970,359"
76,Maine!!Estimate,"1,385,340","79,753","165,876","169,999","169,264","101,581","110,528","185,668","94,186","33,039",45.1,"1,139,849","1,094,878","377,772"
80,Maryland!!Estimate,"6,164,660","379,802","804,952","840,212","772,926","408,464","416,883","608,167","317,893","116,719",39.7,"4,817,929","4,591,262","1,288,293"
84,Massachusetts!!Estimate,"6,981,974","491,572","968,621","907,291","858,029","474,572","478,771","731,781","381,747","146,572",40.3,"5,645,986","5,339,036","1,547,748"
88,Michigan!!Estimate,"10,034,118","687,971","1,315,373","1,219,208","1,201,643","649,226","715,940","1,123,560","552,700","201,302",40.3,"7,927,890","7,525,994","2,305,604"
92,Minnesota!!Estimate,"5,717,184","364,158","743,021","781,414","656,345","348,705","394,033","582,404","295,745","116,898",39.0,"4,428,971","4,213,047","1,230,847"
96,Mississippi!!Estimate,"2,940,057","209,168","351,516","379,896","353,218","166,777","198,731","309,684","153,908","49,592",38.9,"2,263,972","2,130,887","631,014"
100,Missouri!!Estimate,"6,177,957","411,856","808,963","794,549","714,086","375,467","429,809","651,424","342,439","119,273",39.1,"4,815,166","4,564,505","1,366,113"
104,Montana!!Estimate,"1,122,867","75,198","145,978","146,403","123,314","64,992","78,615","138,176","67,441","20,519",40.2,"888,685","844,681","274,276"
108,Nebraska!!Estimate,"1,967,923","135,424","250,983","263,908","215,803","106,172","128,331","196,677","100,598","37,622",37.4,"1,493,226","1,409,447","411,867"
112,Nevada!!Estimate,"3,177,772","194,836","456,422","440,794","397,253","198,602","192,290","324,759","170,974","42,758",39.0,"2,488,119","2,377,199","652,110"
116,New Hampshire!!Estimate,"1,395,231","83,149","182,003","172,049","171,645","103,977","113,123","170,182","82,122","29,679",43.3,"1,143,538","1,089,913","349,014"
120,New Jersey!!Estimate,"9,261,699","569,581","1,183,821","1,233,720","1,195,456","625,009","632,491","924,597","501,190","185,939",40.4,"7,271,522","6,947,554","1,997,412"
124,New Mexico!!Estimate,"2,113,344","145,968","274,314","275,394","238,273","124,063","136,301","241,981","125,380","37,423",39.4,"1,657,869","1,571,214","487,713"
128,New York!!Estimate,"19,677,151","1,298,992","2,762,250","2,536,794","2,405,807","1,305,675","1,317,119","2,032,279","1,097,128","435,189",40.0,"15,695,913","14,933,275","4,346,590"
132,North Carolina!!Estimate,"10,698,973","738,731","1,420,429","1,376,684","1,345,894","664,013","698,486","1,115,768","576,762","174,084",39.2,"8,406,045","7,955,246","2,286,250"
136,North Dakota!!Estimate,"779,261","57,873","112,725","106,486","75,736","42,226","47,320","75,806","37,296","17,191",36.2,"598,296","560,672","159,780"
140,Ohio!!Estimate,"11,756,058","766,640","1,539,071","1,475,428","1,402,439","740,167","805,159","1,287,086","647,241","234,338",39.9,"9,197,902","8,734,215","2,650,395"
144,Oklahoma!!Estimate,"4,019,800","289,564","534,957","532,522","456,850","223,204","251,612","390,170","208,329","63,497",37.1,"3,066,378","2,894,499","813,730"
148,Oregon!!Estimate,"4,240,137","259,457","596,347","593,849","524,584","242,699","269,737","487,945","245,665","83,104",40.5,"3,407,770","3,253,969","977,929"
152,Pennsylvania!!Estimate,"12,972,008","829,180","1,677,321","1,623,572","1,541,463","847,170","923,164","1,467,823","771,084","300,147",40.9,"10,349,850","9,801,876","3,103,368"
156,Rhode Island!!Estimate,"1,093,734","76,125","150,979","137,922","129,195","73,528","80,450","120,395","62,229","23,493",40.7,"890,588","837,857","255,054"
160,South Carolina!!Estimate,"5,282,634","351,883","663,662","667,920","630,345","326,972","367,405","608,018","308,314","92,286",40.5,"4,165,492","3,951,168","1,232,735"
164,South Dakota!!Estimate,"909,824","60,455","111,152","116,031","97,020","51,885","63,738","101,562","45,076","19,271",38.5,"690,843","653,047","203,864"
168,Tennessee!!Estimate,"7,051,339","472,131","964,188","909,015","867,729","449,565","459,649","729,543","371,939","116,482",39.2,"5,516,206","5,244,890","1,494,371"
172,Texas!!Estimate,"30,029,572","2,145,802","4,329,357","4,238,922","3,687,865","1,641,396","1,662,758","2,461,155","1,191,925","384,005",35.6,"22,589,909","21,330,100","5,005,866"
176,Utah!!Estimate,"3,380,800","299,515","494,776","461,217","373,195","149,430","160,595","245,616","120,140","37,943",32.1,"2,450,207","2,294,743","496,260"
180,Vermont!!Estimate,"647,064","43,805","77,515","80,179","75,793","41,144","53,185","83,560","42,914","13,353",43.2,"533,330","498,934","172,615"
184,Virginia!!Estimate,"8,683,619","602,285","1,156,622","1,180,820","1,068,270","557,202","553,826","858,719","453,375","149,948",39.0,"6,821,532","6,461,475","1,800,050"
188,Washington!!Estimate,"7,785,786","499,354","1,176,297","1,115,638","936,835","451,753","480,544","786,321","390,798","132,023",38.4,"6,141,759","5,884,735","1,602,427"
192,West Virginia!!Estimate,"1,775,156","114,325","207,092","216,666","221,995","114,295","126,356","224,674","115,024","36,464",42.9,"1,423,613","1,352,917","452,834"
196,Wisconsin!!Estimate,"5,892,539","407,006","733,729","742,993","692,508","392,381","424,503","658,466","324,703","119,217",40.4,"4,650,759","4,410,387","1,355,209"
200,Wyoming!!Estimate,"581,381","36,882","72,434","81,607","64,361","35,054","38,352","68,377","31,530","8,081",39.1,"451,778","427,524","130,749"
204,Puerto Rico!!Estimate,"3,221,789","216,771","405,834","398,749","404,722","215,212","223,075","383,979","275,913","96,954",44.7,"2,703,453","2,579,711","893,284"

In [99]:
new_row_names = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52']
final_population_df.index = new_row_names

final_population_df.head (200)

Label (Grouping),index,Total population,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age (years),18 years and over,21 years and over,62 years and over
1,Alabama!!Estimate,"5,074,296","345,126","652,152","632,416","617,680","318,087","341,576","546,189","281,791","85,033",39.6,"3,963,268","3,740,839","1,115,768"
2,Alaska!!Estimate,"733,583","52,259","113,900","104,911","81,813","43,503","43,617","68,896","26,870","5,708",35.9,"557,838","530,734","127,751"
3,Arizona!!Estimate,"7,359,197","522,484","1,018,691","926,470","855,266","414,587","456,688","781,078","471,625","129,251",38.8,"5,771,594","5,479,621","1,654,674"
4,Arkansas!!Estimate,"3,045,637","209,906","385,877","387,640","363,403","181,881","199,981","315,159","169,508","54,175",38.9,"2,349,805","2,224,439","658,015"
5,California!!Estimate,"39,029,342","2,639,787","5,744,459","5,395,388","4,877,813","2,356,663","2,333,548","3,568,539","1,878,688","711,675",37.9,"30,530,336","28,971,158","7,528,702"
6,Colorado!!Estimate,"5,839,926","395,695","915,942","860,355","704,694","327,914","359,438","562,352","268,623","84,686",37.7,"4,628,831","4,402,108","1,129,744"
7,Connecticut!!Estimate,"3,626,205","243,507","450,510","460,313","455,401","256,256","258,996","381,828","199,913","81,971",40.9,"2,895,781","2,739,659","818,271"
8,Delaware!!Estimate,"1,018,396","59,981","130,563","125,307","112,870","65,121","78,000","126,996","66,312","18,872",41.5,"810,169","769,624","260,120"
9,District of Columbia!!Estimate,"671,803","48,043","145,253","111,221","71,561","30,859","32,983","50,100","27,846","9,408",34.9,"547,559","519,804","106,696"
10,Florida!!Estimate,"22,244,823","1,340,486","2,783,761","2,799,499","2,734,163","1,472,092","1,520,481","2,604,014","1,638,608","551,792",42.7,"17,949,929","17,173,813","5,701,562"
11,Georgia!!Estimate,"10,912,876","771,563","1,483,997","1,469,050","1,399,249","681,208","655,201","998,558","502,309","143,408",37.6,"8,407,208","7,944,999","2,032,087"
12,Hawaii!!Estimate,"1,440,196","89,347","190,091","192,131","170,144","85,230","91,593","163,041","94,511","37,102",40.8,"1,143,330","1,096,073","349,372"
13,Idaho!!Estimate,"1,939,033","141,188","250,343","256,103","219,658","108,296","116,248","200,204","98,886","30,440",37.5,"1,474,413","1,393,829","399,602"
14,Illinois!!Estimate,"12,582,032","850,982","1,689,818","1,673,268","1,557,011","798,387","809,415","1,262,869","656,343","245,728",39.1,"9,865,826","9,382,977","2,642,662"
15,Indiana!!Estimate,"6,833,037","489,814","886,951","866,145","815,195","414,046","444,697","688,473","350,997","117,956",38.2,"5,263,663","4,970,757","1,424,537"
16,Iowa!!Estimate,"3,200,517","231,721","401,666","405,073","361,104","188,738","214,051","341,121","179,782","67,976",38.9,"2,483,769","2,343,680","716,881"
17,Kansas!!Estimate,"2,937,150","218,626","377,319","382,629","323,536","171,124","183,941","296,501","151,007","58,834",37.6,"2,248,938","2,119,340","613,340"
18,Kentucky!!Estimate,"4,512,310","301,356","587,159","569,323","557,593","279,552","306,759","477,806","235,960","77,347",39.4,"3,507,430","3,332,221","975,245"
19,Louisiana!!Estimate,"4,590,241","315,728","592,066","611,300","533,153","262,705","316,836","472,005","236,926","71,130",38.2,"3,531,381","3,342,828","970,359"
20,Maine!!Estimate,"1,385,340","79,753","165,876","169,999","169,264","101,581","110,528","185,668","94,186","33,039",45.1,"1,139,849","1,094,878","377,772"
21,Maryland!!Estimate,"6,164,660","379,802","804,952","840,212","772,926","408,464","416,883","608,167","317,893","116,719",39.7,"4,817,929","4,591,262","1,288,293"
22,Massachusetts!!Estimate,"6,981,974","491,572","968,621","907,291","858,029","474,572","478,771","731,781","381,747","146,572",40.3,"5,645,986","5,339,036","1,547,748"
23,Michigan!!Estimate,"10,034,118","687,971","1,315,373","1,219,208","1,201,643","649,226","715,940","1,123,560","552,700","201,302",40.3,"7,927,890","7,525,994","2,305,604"
24,Minnesota!!Estimate,"5,717,184","364,158","743,021","781,414","656,345","348,705","394,033","582,404","295,745","116,898",39.0,"4,428,971","4,213,047","1,230,847"
25,Mississippi!!Estimate,"2,940,057","209,168","351,516","379,896","353,218","166,777","198,731","309,684","153,908","49,592",38.9,"2,263,972","2,130,887","631,014"
26,Missouri!!Estimate,"6,177,957","411,856","808,963","794,549","714,086","375,467","429,809","651,424","342,439","119,273",39.1,"4,815,166","4,564,505","1,366,113"
27,Montana!!Estimate,"1,122,867","75,198","145,978","146,403","123,314","64,992","78,615","138,176","67,441","20,519",40.2,"888,685","844,681","274,276"
28,Nebraska!!Estimate,"1,967,923","135,424","250,983","263,908","215,803","106,172","128,331","196,677","100,598","37,622",37.4,"1,493,226","1,409,447","411,867"
29,Nevada!!Estimate,"3,177,772","194,836","456,422","440,794","397,253","198,602","192,290","324,759","170,974","42,758",39.0,"2,488,119","2,377,199","652,110"
30,New Hampshire!!Estimate,"1,395,231","83,149","182,003","172,049","171,645","103,977","113,123","170,182","82,122","29,679",43.3,"1,143,538","1,089,913","349,014"
31,New Jersey!!Estimate,"9,261,699","569,581","1,183,821","1,233,720","1,195,456","625,009","632,491","924,597","501,190","185,939",40.4,"7,271,522","6,947,554","1,997,412"
32,New Mexico!!Estimate,"2,113,344","145,968","274,314","275,394","238,273","124,063","136,301","241,981","125,380","37,423",39.4,"1,657,869","1,571,214","487,713"
33,New York!!Estimate,"19,677,151","1,298,992","2,762,250","2,536,794","2,405,807","1,305,675","1,317,119","2,032,279","1,097,128","435,189",40.0,"15,695,913","14,933,275","4,346,590"
34,North Carolina!!Estimate,"10,698,973","738,731","1,420,429","1,376,684","1,345,894","664,013","698,486","1,115,768","576,762","174,084",39.2,"8,406,045","7,955,246","2,286,250"
35,North Dakota!!Estimate,"779,261","57,873","112,725","106,486","75,736","42,226","47,320","75,806","37,296","17,191",36.2,"598,296","560,672","159,780"
36,Ohio!!Estimate,"11,756,058","766,640","1,539,071","1,475,428","1,402,439","740,167","805,159","1,287,086","647,241","234,338",39.9,"9,197,902","8,734,215","2,650,395"
37,Oklahoma!!Estimate,"4,019,800","289,564","534,957","532,522","456,850","223,204","251,612","390,170","208,329","63,497",37.1,"3,066,378","2,894,499","813,730"
38,Oregon!!Estimate,"4,240,137","259,457","596,347","593,849","524,584","242,699","269,737","487,945","245,665","83,104",40.5,"3,407,770","3,253,969","977,929"
39,Pennsylvania!!Estimate,"12,972,008","829,180","1,677,321","1,623,572","1,541,463","847,170","923,164","1,467,823","771,084","300,147",40.9,"10,349,850","9,801,876","3,103,368"
40,Rhode Island!!Estimate,"1,093,734","76,125","150,979","137,922","129,195","73,528","80,450","120,395","62,229","23,493",40.7,"890,588","837,857","255,054"
41,South Carolina!!Estimate,"5,282,634","351,883","663,662","667,920","630,345","326,972","367,405","608,018","308,314","92,286",40.5,"4,165,492","3,951,168","1,232,735"
42,South Dakota!!Estimate,"909,824","60,455","111,152","116,031","97,020","51,885","63,738","101,562","45,076","19,271",38.5,"690,843","653,047","203,864"
43,Tennessee!!Estimate,"7,051,339","472,131","964,188","909,015","867,729","449,565","459,649","729,543","371,939","116,482",39.2,"5,516,206","5,244,890","1,494,371"
44,Texas!!Estimate,"30,029,572","2,145,802","4,329,357","4,238,922","3,687,865","1,641,396","1,662,758","2,461,155","1,191,925","384,005",35.6,"22,589,909","21,330,100","5,005,866"
45,Utah!!Estimate,"3,380,800","299,515","494,776","461,217","373,195","149,430","160,595","245,616","120,140","37,943",32.1,"2,450,207","2,294,743","496,260"
46,Vermont!!Estimate,"647,064","43,805","77,515","80,179","75,793","41,144","53,185","83,560","42,914","13,353",43.2,"533,330","498,934","172,615"
47,Virginia!!Estimate,"8,683,619","602,285","1,156,622","1,180,820","1,068,270","557,202","553,826","858,719","453,375","149,948",39.0,"6,821,532","6,461,475","1,800,050"
48,Washington!!Estimate,"7,785,786","499,354","1,176,297","1,115,638","936,835","451,753","480,544","786,321","390,798","132,023",38.4,"6,141,759","5,884,735","1,602,427"
49,West Virginia!!Estimate,"1,775,156","114,325","207,092","216,666","221,995","114,295","126,356","224,674","115,024","36,464",42.9,"1,423,613","1,352,917","452,834"
50,Wisconsin!!Estimate,"5,892,539","407,006","733,729","742,993","692,508","392,381","424,503","658,466","324,703","119,217",40.4,"4,650,759","4,410,387","1,355,209"
51,Wyoming!!Estimate,"581,381","36,882","72,434","81,607","64,361","35,054","38,352","68,377","31,530","8,081",39.1,"451,778","427,524","130,749"
52,Puerto Rico!!Estimate,"3,221,789","216,771","405,834","398,749","404,722","215,212","223,075","383,979","275,913","96,954",44.7,"2,703,453","2,579,711","893,284"

In [100]:
final_population_df.columns

Index(['index', '    Total population', '        20 to 24 years',
       '        25 to 34 years', '        35 to 44 years',
       '        45 to 54 years', '        55 to 59 years',
       '        60 to 64 years', '        65 to 74 years',
       '        75 to 84 years', '        85 years and over',
       '        Median age (years)', '        18 years and over',
       '        21 years and over', '        62 years and over'],
      dtype='object', name='Label (Grouping)')

In [101]:
new_column_names = ['State', 'Total population', '20 to 24 years',
       '25 to 34 years', '35 to 44 years',
       '45 to 54 years', '55 to 59 years',
       '60 to 64 years', '65 to 74 years',
       '75 to 84 years', '85 years and over',
       'Median age', '18 years and over',
       '21 years and over', '62 years and over']


final_population_df.columns = new_column_names

In [102]:
new_index_name = 'Index'

final_population_df = final_population_df.rename_axis(new_index_name)

final_population_df.head (200)

,State,Total population,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age,18 years and over,21 years and over,62 years and over
Index,,,,,,,,,,,,,,,
1,Alabama!!Estimate,"5,074,296","345,126","652,152","632,416","617,680","318,087","341,576","546,189","281,791","85,033",39.6,"3,963,268","3,740,839","1,115,768"
2,Alaska!!Estimate,"733,583","52,259","113,900","104,911","81,813","43,503","43,617","68,896","26,870","5,708",35.9,"557,838","530,734","127,751"
3,Arizona!!Estimate,"7,359,197","522,484","1,018,691","926,470","855,266","414,587","456,688","781,078","471,625","129,251",38.8,"5,771,594","5,479,621","1,654,674"
4,Arkansas!!Estimate,"3,045,637","209,906","385,877","387,640","363,403","181,881","199,981","315,159","169,508","54,175",38.9,"2,349,805","2,224,439","658,015"
5,California!!Estimate,"39,029,342","2,639,787","5,744,459","5,395,388","4,877,813","2,356,663","2,333,548","3,568,539","1,878,688","711,675",37.9,"30,530,336","28,971,158","7,528,702"
6,Colorado!!Estimate,"5,839,926","395,695","915,942","860,355","704,694","327,914","359,438","562,352","268,623","84,686",37.7,"4,628,831","4,402,108","1,129,744"
7,Connecticut!!Estimate,"3,626,205","243,507","450,510","460,313","455,401","256,256","258,996","381,828","199,913","81,971",40.9,"2,895,781","2,739,659","818,271"
8,Delaware!!Estimate,"1,018,396","59,981","130,563","125,307","112,870","65,121","78,000","126,996","66,312","18,872",41.5,"810,169","769,624","260,120"
9,District of Columbia!!Estimate,"671,803","48,043","145,253","111,221","71,561","30,859","32,983","50,100","27,846","9,408",34.9,"547,559","519,804","106,696"
10,Florida!!Estimate,"22,244,823","1,340,486","2,783,761","2,799,499","2,734,163","1,472,092","1,520,481","2,604,014","1,638,608","551,792",42.7,"17,949,929","17,173,813","5,701,562"
11,Georgia!!Estimate,"10,912,876","771,563","1,483,997","1,469,050","1,399,249","681,208","655,201","998,558","502,309","143,408",37.6,"8,407,208","7,944,999","2,032,087"
12,Hawaii!!Estimate,"1,440,196","89,347","190,091","192,131","170,144","85,230","91,593","163,041","94,511","37,102",40.8,"1,143,330","1,096,073","349,372"
13,Idaho!!Estimate,"1,939,033","141,188","250,343","256,103","219,658","108,296","116,248","200,204","98,886","30,440",37.5,"1,474,413","1,393,829","399,602"
14,Illinois!!Estimate,"12,582,032","850,982","1,689,818","1,673,268","1,557,011","798,387","809,415","1,262,869","656,343","245,728",39.1,"9,865,826","9,382,977","2,642,662"
15,Indiana!!Estimate,"6,833,037","489,814","886,951","866,145","815,195","414,046","444,697","688,473","350,997","117,956",38.2,"5,263,663","4,970,757","1,424,537"
16,Iowa!!Estimate,"3,200,517","231,721","401,666","405,073","361,104","188,738","214,051","341,121","179,782","67,976",38.9,"2,483,769","2,343,680","716,881"
17,Kansas!!Estimate,"2,937,150","218,626","377,319","382,629","323,536","171,124","183,941","296,501","151,007","58,834",37.6,"2,248,938","2,119,340","613,340"
18,Kentucky!!Estimate,"4,512,310","301,356","587,159","569,323","557,593","279,552","306,759","477,806","235,960","77,347",39.4,"3,507,430","3,332,221","975,245"
19,Louisiana!!Estimate,"4,590,241","315,728","592,066","611,300","533,153","262,705","316,836","472,005","236,926","71,130",38.2,"3,531,381","3,342,828","970,359"
20,Maine!!Estimate,"1,385,340","79,753","165,876","169,999","169,264","101,581","110,528","185,668","94,186","33,039",45.1,"1,139,849","1,094,878","377,772"
21,Maryland!!Estimate,"6,164,660","379,802","804,952","840,212","772,926","408,464","416,883","608,167","317,893","116,719",39.7,"4,817,929","4,591,262","1,288,293"
22,Massachusetts!!Estimate,"6,981,974","491,572","968,621","907,291","858,029","474,572","478,771","731,781","381,747","146,572",40.3,"5,645,986","5,339,036","1,547,748"
23,Michigan!!Estimate,"10,034,118","687,971","1,315,373","1,219,208","1,201,643","649,226","715,940","1,123,560","552,700","201,302",40.3,"7,927,890","7,525,994","2,305,604"
24,Minnesota!!Estimate,"5,717,184","364,158","743,021","781,414","656,345","348,705","394,033","582,404","295,745","116,898",39.0,"4,428,971","4,213,047","1,230,847"
25,Mississippi!!Estimate,"2,940,057","209,168","351,516","379,896","353,218","166,777","198,731","309,684","153,908","49,592",38.9,"2,263,972","2,130,887","631,014"
26,Missouri!!Estimate,"6,177,957","411,856","808,963","794,549","714,086","375,467","429,809","651,424","342,439","119,273",39.1,"4,815,166","4,564,505","1,366,113"
27,Montana!!Estimate,"1,122,867","75,198","145,978","146,403","123,314","64,992","78,615","138,176","67,441","20,519",40.2,"888,685","844,681","274,276"
28,Nebraska!!Estimate,"1,967,923","135,424","250,983","263,908","215,803","106,172","128,331","196,677","100,598","37,622",37.4,"1,493,226","1,409,447","411,867"
29,Nevada!!Estimate,"3,177,772","194,836","456,422","440,794","397,253","198,602","192,290","324,759","170,974","42,758",39.0,"2,488,119","2,377,199","652,110"
30,New Hampshire!!Estimate,"1,395,231","83,149","182,003","172,049","171,645","103,977","113,123","170,182","82,122","29,679",43.3,"1,143,538","1,089,913","349,014"
31,New Jersey!!Estimate,"9,261,699","569,581","1,183,821","1,233,720","1,195,456","625,009","632,491","924,597","501,190","185,939",40.4,"7,271,522","6,947,554","1,997,412"
32,New Mexico!!Estimate,"2,113,344","145,968","274,314","275,394","238,273","124,063","136,301","241,981","125,380","37,423",39.4,"1,657,869","1,571,214","487,713"
33,New York!!Estimate,"19,677,151","1,298,992","2,762,250","2,536,794","2,405,807","1,305,675","1,317,119","2,032,279","1,097,128","435,189",40.0,"15,695,913","14,933,275","4,346,590"
34,North Carolina!!Estimate,"10,698,973","738,731","1,420,429","1,376,684","1,345,894","664,013","698,486","1,115,768","576,762","174,084",39.2,"8,406,045","7,955,246","2,286,250"
35,North Dakota!!Estimate,"779,261","57,873","112,725","106,486","75,736","42,226","47,320","75,806","37,296","17,191",36.2,"598,296","560,672","159,780"
36,Ohio!!Estimate,"11,756,058","766,640","1,539,071","1,475,428","1,402,439","740,167","805,159","1,287,086","647,241","234,338",39.9,"9,197,902","8,734,215","2,650,395"
37,Oklahoma!!Estimate,"4,019,800","289,564","534,957","532,522","456,850","223,204","251,612","390,170","208,329","63,497",37.1,"3,066,378","2,894,499","813,730"
38,Oregon!!Estimate,"4,240,137","259,457","596,347","593,849","524,584","242,699","269,737","487,945","245,665","83,104",40.5,"3,407,770","3,253,969","977,929"
39,Pennsylvania!!Estimate,"12,972,008","829,180","1,677,321","1,623,572","1,541,463","847,170","923,164","1,467,823","771,084","300,147",40.9,"10,349,850","9,801,876","3,103,368"
40,Rhode Island!!Estimate,"1,093,734","76,125","150,979","137,922","129,195","73,528","80,450","120,395","62,229","23,493",40.7,"890,588","837,857","255,054"
41,South Carolina!!Estimate,"5,282,634","351,883","663,662","667,920","630,345","326,972","367,405","608,018","308,314","92,286",40.5,"4,165,492","3,951,168","1,232,735"
42,South Dakota!!Estimate,"909,824","60,455","111,152","116,031","97,020","51,885","63,738","101,562","45,076","19,271",38.5,"690,843","653,047","203,864"
43,Tennessee!!Estimate,"7,051,339","472,131","964,188","909,015","867,729","449,565","459,649","729,543","371,939","116,482",39.2,"5,516,206","5,244,890","1,494,371"
44,Texas!!Estimate,"30,029,572","2,145,802","4,329,357","4,238,922","3,687,865","1,641,396","1,662,758","2,461,155","1,191,925","384,005",35.6,"22,589,909","21,330,100","5,005,866"
45,Utah!!Estimate,"3,380,800","299,515","494,776","461,217","373,195","149,430","160,595","245,616","120,140","37,943",32.1,"2,450,207","2,294,743","496,260"
46,Vermont!!Estimate,"647,064","43,805","77,515","80,179","75,793","41,144","53,185","83,560","42,914","13,353",43.2,"533,330","498,934","172,615"
47,Virginia!!Estimate,"8,683,619","602,285","1,156,622","1,180,820","1,068,270","557,202","553,826","858,719","453,375","149,948",39.0,"6,821,532","6,461,475","1,800,050"
48,Washington!!Estimate,"7,785,786","499,354","1,176,297","1,115,638","936,835","451,753","480,544","786,321","390,798","132,023",38.4,"6,141,759","5,884,735","1,602,427"
49,West Virginia!!Estimate,"1,775,156","114,325","207,092","216,666","221,995","114,295","126,356","224,674","115,024","36,464",42.9,"1,423,613","1,352,917","452,834"
50,Wisconsin!!Estimate,"5,892,539","407,006","733,729","742,993","692,508","392,381","424,503","658,466","324,703","119,217",40.4,"4,650,759","4,410,387","1,355,209"
51,Wyoming!!Estimate,"581,381","36,882","72,434","81,607","64,361","35,054","38,352","68,377","31,530","8,081",39.1,"451,778","427,524","130,749"
52,Puerto Rico!!Estimate,"3,221,789","216,771","405,834","398,749","404,722","215,212","223,075","383,979","275,913","96,954",44.7,"2,703,453","2,579,711","893,284"

In [103]:
final_population_df.columns

Index(['State', 'Total population', '20 to 24 years', '25 to 34 years',
       '35 to 44 years', '45 to 54 years', '55 to 59 years', '60 to 64 years',
       '65 to 74 years', '75 to 84 years', '85 years and over', 'Median age',
       '18 years and over', '21 years and over', '62 years and over'],
      dtype='object')

In [104]:
new_values = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico']

final_population_df['State'] = new_values

final_population_df.head (200)

,State,Total population,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age,18 years and over,21 years and over,62 years and over
Index,,,,,,,,,,,,,,,
1,Alabama,"5,074,296","345,126","652,152","632,416","617,680","318,087","341,576","546,189","281,791","85,033",39.6,"3,963,268","3,740,839","1,115,768"
2,Alaska,"733,583","52,259","113,900","104,911","81,813","43,503","43,617","68,896","26,870","5,708",35.9,"557,838","530,734","127,751"
3,Arizona,"7,359,197","522,484","1,018,691","926,470","855,266","414,587","456,688","781,078","471,625","129,251",38.8,"5,771,594","5,479,621","1,654,674"
4,Arkansas,"3,045,637","209,906","385,877","387,640","363,403","181,881","199,981","315,159","169,508","54,175",38.9,"2,349,805","2,224,439","658,015"
5,California,"39,029,342","2,639,787","5,744,459","5,395,388","4,877,813","2,356,663","2,333,548","3,568,539","1,878,688","711,675",37.9,"30,530,336","28,971,158","7,528,702"
6,Colorado,"5,839,926","395,695","915,942","860,355","704,694","327,914","359,438","562,352","268,623","84,686",37.7,"4,628,831","4,402,108","1,129,744"
7,Connecticut,"3,626,205","243,507","450,510","460,313","455,401","256,256","258,996","381,828","199,913","81,971",40.9,"2,895,781","2,739,659","818,271"
8,Delaware,"1,018,396","59,981","130,563","125,307","112,870","65,121","78,000","126,996","66,312","18,872",41.5,"810,169","769,624","260,120"
9,District of Columbia,"671,803","48,043","145,253","111,221","71,561","30,859","32,983","50,100","27,846","9,408",34.9,"547,559","519,804","106,696"
10,Florida,"22,244,823","1,340,486","2,783,761","2,799,499","2,734,163","1,472,092","1,520,481","2,604,014","1,638,608","551,792",42.7,"17,949,929","17,173,813","5,701,562"
11,Georgia,"10,912,876","771,563","1,483,997","1,469,050","1,399,249","681,208","655,201","998,558","502,309","143,408",37.6,"8,407,208","7,944,999","2,032,087"
12,Hawaii,"1,440,196","89,347","190,091","192,131","170,144","85,230","91,593","163,041","94,511","37,102",40.8,"1,143,330","1,096,073","349,372"
13,Idaho,"1,939,033","141,188","250,343","256,103","219,658","108,296","116,248","200,204","98,886","30,440",37.5,"1,474,413","1,393,829","399,602"
14,Illinois,"12,582,032","850,982","1,689,818","1,673,268","1,557,011","798,387","809,415","1,262,869","656,343","245,728",39.1,"9,865,826","9,382,977","2,642,662"
15,Indiana,"6,833,037","489,814","886,951","866,145","815,195","414,046","444,697","688,473","350,997","117,956",38.2,"5,263,663","4,970,757","1,424,537"
16,Iowa,"3,200,517","231,721","401,666","405,073","361,104","188,738","214,051","341,121","179,782","67,976",38.9,"2,483,769","2,343,680","716,881"
17,Kansas,"2,937,150","218,626","377,319","382,629","323,536","171,124","183,941","296,501","151,007","58,834",37.6,"2,248,938","2,119,340","613,340"
18,Kentucky,"4,512,310","301,356","587,159","569,323","557,593","279,552","306,759","477,806","235,960","77,347",39.4,"3,507,430","3,332,221","975,245"
19,Louisana,"4,590,241","315,728","592,066","611,300","533,153","262,705","316,836","472,005","236,926","71,130",38.2,"3,531,381","3,342,828","970,359"
20,Maine,"1,385,340","79,753","165,876","169,999","169,264","101,581","110,528","185,668","94,186","33,039",45.1,"1,139,849","1,094,878","377,772"
21,Maryland,"6,164,660","379,802","804,952","840,212","772,926","408,464","416,883","608,167","317,893","116,719",39.7,"4,817,929","4,591,262","1,288,293"
22,Massachusetts,"6,981,974","491,572","968,621","907,291","858,029","474,572","478,771","731,781","381,747","146,572",40.3,"5,645,986","5,339,036","1,547,748"
23,Michigan,"10,034,118","687,971","1,315,373","1,219,208","1,201,643","649,226","715,940","1,123,560","552,700","201,302",40.3,"7,927,890","7,525,994","2,305,604"
24,Minnesota,"5,717,184","364,158","743,021","781,414","656,345","348,705","394,033","582,404","295,745","116,898",39.0,"4,428,971","4,213,047","1,230,847"
25,Mississippi,"2,940,057","209,168","351,516","379,896","353,218","166,777","198,731","309,684","153,908","49,592",38.9,"2,263,972","2,130,887","631,014"
26,Missouri,"6,177,957","411,856","808,963","794,549","714,086","375,467","429,809","651,424","342,439","119,273",39.1,"4,815,166","4,564,505","1,366,113"
27,Montana,"1,122,867","75,198","145,978","146,403","123,314","64,992","78,615","138,176","67,441","20,519",40.2,"888,685","844,681","274,276"
28,Nebraska,"1,967,923","135,424","250,983","263,908","215,803","106,172","128,331","196,677","100,598","37,622",37.4,"1,493,226","1,409,447","411,867"
29,Nevada,"3,177,772","194,836","456,422","440,794","397,253","198,602","192,290","324,759","170,974","42,758",39.0,"2,488,119","2,377,199","652,110"
30,New Hampshire,"1,395,231","83,149","182,003","172,049","171,645","103,977","113,123","170,182","82,122","29,679",43.3,"1,143,538","1,089,913","349,014"
31,New Jersey,"9,261,699","569,581","1,183,821","1,233,720","1,195,456","625,009","632,491","924,597","501,190","185,939",40.4,"7,271,522","6,947,554","1,997,412"
32,New Mexico,"2,113,344","145,968","274,314","275,394","238,273","124,063","136,301","241,981","125,380","37,423",39.4,"1,657,869","1,571,214","487,713"
33,New York,"19,677,151","1,298,992","2,762,250","2,536,794","2,405,807","1,305,675","1,317,119","2,032,279","1,097,128","435,189",40.0,"15,695,913","14,933,275","4,346,590"
34,North Carolina,"10,698,973","738,731","1,420,429","1,376,684","1,345,894","664,013","698,486","1,115,768","576,762","174,084",39.2,"8,406,045","7,955,246","2,286,250"
35,North Dakota,"779,261","57,873","112,725","106,486","75,736","42,226","47,320","75,806","37,296","17,191",36.2,"598,296","560,672","159,780"
36,Ohio,"11,756,058","766,640","1,539,071","1,475,428","1,402,439","740,167","805,159","1,287,086","647,241","234,338",39.9,"9,197,902","8,734,215","2,650,395"
37,Oklahoma,"4,019,800","289,564","534,957","532,522","456,850","223,204","251,612","390,170","208,329","63,497",37.1,"3,066,378","2,894,499","813,730"
38,Oregon,"4,240,137","259,457","596,347","593,849","524,584","242,699","269,737","487,945","245,665","83,104",40.5,"3,407,770","3,253,969","977,929"
39,Pennsylvania,"12,972,008","829,180","1,677,321","1,623,572","1,541,463","847,170","923,164","1,467,823","771,084","300,147",40.9,"10,349,850","9,801,876","3,103,368"
40,Rhode Island,"1,093,734","76,125","150,979","137,922","129,195","73,528","80,450","120,395","62,229","23,493",40.7,"890,588","837,857","255,054"
41,South Carolina,"5,282,634","351,883","663,662","667,920","630,345","326,972","367,405","608,018","308,314","92,286",40.5,"4,165,492","3,951,168","1,232,735"
42,South Dakota,"909,824","60,455","111,152","116,031","97,020","51,885","63,738","101,562","45,076","19,271",38.5,"690,843","653,047","203,864"
43,Tennessee,"7,051,339","472,131","964,188","909,015","867,729","449,565","459,649","729,543","371,939","116,482",39.2,"5,516,206","5,244,890","1,494,371"
44,Texas,"30,029,572","2,145,802","4,329,357","4,238,922","3,687,865","1,641,396","1,662,758","2,461,155","1,191,925","384,005",35.6,"22,589,909","21,330,100","5,005,866"
45,Utah,"3,380,800","299,515","494,776","461,217","373,195","149,430","160,595","245,616","120,140","37,943",32.1,"2,450,207","2,294,743","496,260"
46,Vermont,"647,064","43,805","77,515","80,179","75,793","41,144","53,185","83,560","42,914","13,353",43.2,"533,330","498,934","172,615"
47,Virginia,"8,683,619","602,285","1,156,622","1,180,820","1,068,270","557,202","553,826","858,719","453,375","149,948",39.0,"6,821,532","6,461,475","1,800,050"
48,Washington,"7,785,786","499,354","1,176,297","1,115,638","936,835","451,753","480,544","786,321","390,798","132,023",38.4,"6,141,759","5,884,735","1,602,427"
49,West Virginia,"1,775,156","114,325","207,092","216,666","221,995","114,295","126,356","224,674","115,024","36,464",42.9,"1,423,613","1,352,917","452,834"
50,Wisconsin,"5,892,539","407,006","733,729","742,993","692,508","392,381","424,503","658,466","324,703","119,217",40.4,"4,650,759","4,410,387","1,355,209"
51,Wyoming,"581,381","36,882","72,434","81,607","64,361","35,054","38,352","68,377","31,530","8,081",39.1,"451,778","427,524","130,749"
52,Puerto Rico,"3,221,789","216,771","405,834","398,749","404,722","215,212","223,075","383,979","275,913","96,954",44.7,"2,703,453","2,579,711","893,284"

In [105]:
csv_file_path = 'Census_Population.csv'


final_population_df.to_csv(csv_file_path, index=False)